- src/flavors/happytrail/jstemplates/pages/achievements.html
- src/flavors/happytrail/jstemplates/pages/scarytrail.html
- src/sa_web/static/js/views/legend-view.js
I've confirmed watching first time users on multiple occasions that the titles "Filter Reports" and "Toggle layers" are confusing. One person from DRCC thought that "Filter Reports" was a noun and not a verb.
I think the labels "Report Types" and "Map Layers" are more clear, as they better describe the things underneath them.
> changed legend titles better labels 'report types and 'map layers'

- src/sa_web/jstemplates/place-form.html
- src/sa_web/static/css/default.css
I replaced the `<p>` tags per issue #160 with divs and a new class .form-field. I also tweaked .drag-marker-* to make the spacing more consistent and applied the .form-field class to `{{ place_config.help_text }}`, also for more consistent spacing.
> Add new class to reduce new form spacing

- src/sa_web/static/css/default.css
When opening "About", "Background", etc. on a large screen, there is no longer the intrusive whitespace left behind when I ripped out the old legend sidebar.
Next steps are some mobile optimizations, such that the footer anchors to the bottom of a small screen and dedicates a lot more screen real estate to viewing the map.
> CSS fix to remove old legend space artefacts

- src/flavors/willamette/config.yml
couple of bugs on the new Willamette flavor: 
* Report icons don't show up between zooms 11 and 13
* The location of a newly added report isn't accurately set
> Fix some bugs for Willamette flavor

- app-requirements.txt
Commented out gevent, as it's not necessary.
> Requirements doc update

- concat.js
`npm run build` will error out if a flavor doesn't have a `static/js/views` directory and a `static/css`, so this PR fixes that.
Removed the `dataset-form-view` view, which no longer exists.
> Fix deployment bug

- src/flavors/duwamish_flavor/config.yml
- src/sa_web/static/js/routes.js
- src/sa_web/static/js/views/activity-view.js
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/js/views/place-form-view.js
**UPDATE** -- this should be ready to merge.
----
This PR fixes issue #372 -- but is not quite ready to merge (see comment below).
This PR removes a confusing duplication of the `datasetSlug` parameter in the dynamic form section of the config. Previously, individual dynamic form categories needed to declare the dataset they write to as well as the dataset slug used in urls. Now, the slug is declared in a single place (in the `map.layers` section).
> remove reliance on duplicate datasetSlug parameter in dynamic form config

- src/sa_web/static/css/default.css
- src/sa_web/static/libs/leaflet.sidebar.js
- src/sa_web/static/scss/_media.scss
- Change leaflet-sidebar.js to remove 'active' class from pane when closed
- Move the sidebar to the bottom when window width is below 960px
- Style the sidebar to have a better look
- Change pane close button to 'X' instead of chevron-left when on mobile.
> Make change to sidebar on tablets and phones

- src/sa_web/static/js/views/place-form-view.js
I discovered a bug that generates an `undefined` dataset slug when using the dynamic form with only a single category. This PR fixes it.
> Bug fix in goldpbear/duplicateDatasetSlugParam

- src/sa_web/static/js/utils.js
This new logic branch precludes having to account for every single browser in the wild (and all future browsers yet to come). SImply check the version of the particular browser(s) in question.
> Revised the supported browsers logic

- Gruntfile.js
- concat.js
- src/flavors/duwamish_flavor/config.yml
- src/sa_web/jasmine/spec/javascripts/support/jasmine.yml
- src/sa_web/static/js/views/map-view.js
- src/sa_web/static/libs/esri-leaflet.js
- src/sa_web/templates/base.html
Add support for ESRI's protocol, per #332.
Notes:
- The standard way of interfacing with ESRI endpoints is to dynamically request data from the server as the user pans around on the map. While useful for endpoints with tons of data, for small-scale data this can result in lots of unnecessary HTTP roundtrips. I added a config option, `loadStrategy: all at once` to download all data at the beginning. For obvious reasons, this will be a huge performance hit if used on the wrong endpoint.
- Even in `all at once` mode, GeoJSON primitives like polygons won't render as the user pans, only when the user stops dragging.  See [this Leaflet issue](https://github.com/Leaflet/Leaflet/issues/2814). This isn't specific to ESRI data. Just giving a heads up in case you notice this while testing.
- Because …
> Add ESRI layer support

- src/sa_web/jstemplates/place-detail.html
Fixes #423.
I think this PR should address the immediate problems created by #421 as well, although we may still want to update the metadata on legacy shareabouts places anyway. Having two versions of place model metadata might create issues down the road.
> Place list title support

- src/flavors/bogtobay/config.yml
- src/flavors/duwamish_flavor/config.yml
- src/flavors/greenways/config.yml
- src/flavors/lakewashington/config.yml
- src/flavors/raingardens/config.yml
- src/flavors/snoqualmie/config.yml
- src/flavors/trees/config.yml
- src/flavors/waterfront/config.yml
- src/flavors/willamette/config.yml
- src/sa_web/jstemplates/place-form.html
- src/sa_web/static/js/handlebars-helpers.js
- src/sa_web/static/js/views/place-form-view.js
- src/sa_web/static/js/views/place-list-view.js
Fixes #416, including updates to flavor configs to support form category ordering.
The dynamic form config should now be an array of category objects, where the category name is listed under the `category` property. Here is a representative example:
place_detail:
- category: tree
includeOnForm: true
name: location_type
dataset: trees
icon_url: /static/css/images/markers/marker-tree.png
value: tree
label: _(Tree)
fields: ....
This PR also has some minor additional refactors/cleanup of the dynamic form code.
> Enforce form category ordering

- src/flavors/duwamish_flavor/jstemplates/pages/overview.html
Fixes #437.
@futuresoup -- It turns out that any link with a `rel="internal"` attribute in the HTML tag will get captured by Backbone's router and will be handled client side. So just add that attribute to any links (places, landmarks, pages, etc.) you'd like the client side router to manage.
> Fix page refresh bug

- src/sa_web/jstemplates/place-form.html
- src/sa_web/static/js/views/place-form-view.js
- src/sa_web/static/scss/_content.scss
Addresses one issue of #443.
There is still more work to do on the mobile form submission workflow, but this PR adds a geolocation button to the top of the place form view, alongside the "drag map" instructions.
The button appears on all screen sizes, although we could limit its appearance to certain devices using media queries.
> Add a geolocate button to the place form view

- src/sa_web/static/js/models.js
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/js/views/gis-legend-view.js
- src/sa_web/static/js/views/map-view.js
Addresses #422.
This PR adds the ability to manually set the basemap layer via the story section of the config. To set a basemap layer, use the `basemap` flag on a story element. For example:
```
-  url: report/412
basemap: dark
```
Basemaps set in this way should be listed under the `basemaps` panel in the legend section of the config. ~~and their corresponding layer config should have a `type: basemap` flag set.~~
There is currently no default basemap configuration in story mode, so setting the basemap layer via a story element will keep that basemap layer active until another story element changes it. If a story changes the default basemap, the default basemap will be restored when the user leaves story mode.
Note that this PR refactors a bit of the multi-basemap code introduced in …
> Control basemaps via story mode

- src/flavors/duwamish_flavor/config.yml
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/js/views/basic-layer-view.js
- src/sa_web/static/js/views/layer-view.js
- src/sa_web/static/js/views/map-view.js
Addresses #436.
Fixes #408.
This will have less of an effect on performance than I originally thought, because I thought that we were just hiding, but still rendering, non-visible layers. We already were lazy-rendering. This PR makes it so that we will only make network requests for a layer once it is made visible. Obviously, this has no effect on layer-types like Carto that load progressively.
> Lazy loading layers

- src/sa_web/templates/new_place_email_body.txt
Fixes #26.
This turned out to be a simple fix: we just need to use `place.properties.datasetSlug` in the email body template. Unless I'm missing something, I think this is all we need to do?
I tested things using the following config object:
```
notifications:
on_new_place: true
submitter_email_field: private-submitter_email
```
The email body is generating correctly in the console. I have yet to receive an actual email, but I think that might be because I am not configured to send email from my localhost.
> use datasetSlug in links generated for notifcation emails

- src/sa_web/static/css/default.css
- src/sa_web/static/js/views/place-counter-view.js
- src/sa_web/static/scss/_counter.scss
Fixes #509.
Refactor place-counter-view.js to count models over all place collections
To fix meter bar display issues on Chrome, remove -webkit-appearance: none style and use the -webkit-meter-bar pseudo-selector to enforce styling in Chrome
> Fix meter bar display issues

- src/sa_web/static/js/views/app-view.js
Addresses: #504.
Although I don't completely understand why this helps, passing a {reset: true} parameter to our use of map.fitBounds() in the app view seems to prevent the map render bug we see on an initial load of a polygon landmark.
Not sure if this completely eliminates the problem, as I think it is still possible to trigger this bug through some sequence of interactions after initial page load, but hopefully this cuts down on instances of the bug.
> Pass reset: true option to map.fitBounds()

- src/sa_web/jstemplates/place-form.html
This PR adds two new dynamic form field types: `section_header`, and `section_description`. Neither type accepts input. Use them like this:
```
- name: demographics-header
type: section_header
horizontal_rule: true
content: _(Some section header)
- name: demographics-description
type: section_description
content: _(This is my description of this section of the form)
```
The `horizontal_rule: true` flag is optional, but if it is set to `true` the form will render a horizontal line above the element.
By default, section headers are `<h3>` tags, and section descriptions are `<p>` tags. There is no additional default styling, but style rules can be added in a flavor's `custom.css` file using these selectors: `.form-section-header` and `.form-section-description`. For example:
``` …
```
> add form section header and description field types

- src/flavors/pboakland/config.yml
- src/sa_web/jstemplates/place-form-field-types.html
- src/sa_web/jstemplates/place-form.html
- src/sa_web/static/css/default.css
- src/sa_web/static/js/handlebars-helpers.js
- src/sa_web/static/js/utils.js
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/js/views/place-form-view.js
- src/sa_web/static/scss/_forms.scss
**NOTE:** This PR replicates the same functionality added to the `develop` branch via #543 and #534.
This PR adds dynamic form autocompletion to the `pboakland` flavor. To use the autocomplete feature, add an `autocomplete: true` flag to each form field you'd like tracked. Fields that do not have this flag will not be tracked.
A few notes:
* Autocomplete fields are not category-specific. In other words, if a field with the same name (say, `description`) exists in multiple dynamic form categories, all instances of this field will be autocompleted if a stored value for that field name is found.
* Autocomplete data is stored in localStorage unless localStorage is not available, in which case cookies will be used.
* A light yellow background color is added to form fields that are populated …
> Add form autocompletion to pboakland flavor

- src/sa_web/static/js/views/app-view.js
Passing the reset option seems to elimiate the problem of directly-loaded
landmarks causing a portion of the map to initially not be rendered and the
center of the map to be displayed incorrectly.
Fixes: #504
> Pass reset: true option to map.fitBounds() and map.setView()

- src/sa_web/static/js/views/place-form-view.js
Make sure we reset the dynamic form state if we navigate away from
a rendered form (say, to the list view). Otherwise, it's possible
to corrupt the form's state by returning to the form after navigating
away.
> Call resetFormState() in PlaceFormView on route events

- src/sa_web/static/js/views/place-form-view.js
Fixes a bug that occurs when the dynamic form is show after a Quill editor has been rendered in a place detail view in edit mode.
> Detect if category is selected in place form view postRender()

- src/flavors/duwamish_flavor/config.yml
- src/sa_web/jstemplates/activity-list-item.html
- src/sa_web/jstemplates/place-detail.html
- src/sa_web/static/js/routes.js
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/js/views/layer-view.js
- src/sa_web/static/js/views/place-detail-view.js
Addresses: #527, #549 
This PR is a major refactor of the code that loads places and landmarks. Changes include:
- Support for places with landmark-style urls. If a place model has a field called `url-title`, the value of this field will correspond to the place's url in the app. The underlying Shareabouts-style url will not be used.
- Reduced code duplication and complexity in the AppView. We now have a single `viewPlaceOrLandmark()` method, which accommodates loading from traditional place urls (`report/342`), landmark urls (`/landmark`), and places with landmark-style urls.
- Slight loading performance boost on direct url loads. We might experience quicker load times when we load the app directly to a place or landmark url.
> Refactor place/landmark loading, support landmark-style urls

- src/flavors/duwamish_flavor/config.yml
- src/sa_web/static/css/default.css
- src/sa_web/static/js/views/app-view.js
- src/sa_web/static/scss/_media.scss
- src/sa_web/static/scss/_sidebar.scss
- src/sa_web/static/scss/_ticker.scss
- src/sa_web/static/scss/_variables.scss
- src/sa_web/templates/base.html
Addresses: #561
This PR reinstates the old right-clinging sidebar with activity stream, but adds the ability to turn it on or off in the config. To turn the right-panel sidebar on, set the `show_in_right_panel` flag to `true` in the `activity` section of the config.
Note that to disable the leaflet control version of the activity stream, you'll need to comment out the `id: ticker` section of the leaflet control config. Otherwise, you'll have two activity streams, one in the leaflet controls and one in the right sidebar.
> Add configurable right-panel activity stream

- src/flavors/pboakland/config.yml
- src/flavors/pboakland/jstemplates/place-detail.html
- src/flavors/pboakland/jstemplates/place-form.html
- src/flavors/pboakland/static/css/custom.css
- src/flavors/pboakland/static/js/views/place-detail-view.js
- src/flavors/pboakland/static/js/views/place-form-view.js
Addresses: #576.
This PR makes it possible to declare form fields as admin-only. Admin-only fields will only be visible to logged-in users listed in the `administrators` section of the `place` section of the config. Note that all changes in this PR are contained inside `pboakland` flavor files. I thought this would be better for now, since we may add similar functionality to the base code via the editor/admin panel.
To add administrators, list their social media handles under the `administrators` key:
```
place:
administrators:
- goldpbear
- etc.
adding_supported: true
add_button_label: _(Share your idea!)
...
```
To declare a form field as admin-only, add an `admin_only: true` flag in the form field's section in the config. You can also add an optional message that appears beside …
> Add pboakland admin-only form fields

- src/base/jstemplates/add-places.html
- src/base/jstemplates/centerpoint.html
- src/base/static/js/routes.js
- src/base/static/js/views/app-view.js
- src/base/static/js/views/place-form-view.js
- src/base/static/scss/_content.scss
- src/base/static/scss/_map.scss
- src/base/static/scss/_media.scss
- src/base/static/scss/_variables.scss
- src/base/templates/base.html
- src/flavors/duwamish_flavor/config.yml
- src/flavors/pboakland/static/css/custom.css
Addresses: #587
- Add bottom-clinging report and story buttons on devices with widths below 60em
- Either or both buttons can be configured to display, by commenting out the `add_button_label` property or the `story_button_label` property in the `place` section of the config as appropriate
- Remove bottom-clinging leaflet controls
- After dragging a location with the form view open, adjust form height to nearly full screen
- Add minimize and maximize tabs to the content pane at small screen sizes to toggle content size
- ~~Configure start pages to occupy nearly fullscreen height on devices with widths below 60em~~
- ~~Note that this configuration will be triggered only if there is a page with the `start_page` flag set to `true`, and if the site is accessed at the base url. (In other …
> Landing page enhancements

- src/base/static/scss/_buttons.scss
- prevent form movement on radio/checkbox selection at mobile size
- fix spacing issues with big-button style form controls at mobile size
> Mobile form css hotfixes 610

- src/base/static/js/views/app-view.js
- src/base/static/js/views/place-form-view.js
- src/base/static/scss/_media.scss
Call Leaflet's `invalidateSize()` method to make sure the map correctly re-centers when we change map container dimensions via CSS.
> Fix map re-centering issue

- src/base/static/js/views/activity-view.js
- src/flavors/pboakland/config.yml
Addresses: #616.
- add config param to disable supports in activity stream
- under the `support` section of the config, set the `show_in_activity_stream` flag to `false` to disable supports in the activity stream. This flag will default to `true`.
- show place model title in support activity stream items
- supports will now appear as `So-and-so supported Recreation Center` instead of `So-and-so supported an idea for Parks and Recreation`
> Activity stream support tweaks

- src/base/static/js/views/app-view.js
- src/base/static/scss/_sidebar.scss
Prevent unrecognized body class error.
Also, set background color of the sidebar to prevent the spotlight shadow from being visible in the sidebar when activity content is loading.
> Set right-sidebar-visible class via jquery

- src/base/static/js/views/app-view.js
Addresses: #621. 
This is an effort to avoid a potential race condition between the
CSS transition that resizes the map container to accommodate the
content panel, and the call to invalidateSize() inside showPanel().
The timeout (hopefully) allows the transition to complete and the
new map dimensions to be set before invalidateSize() recenters the map.
> On panel show, call invalidateSize() inside a short timeout

- src/base/jstemplates/activity-list-item.html
- src/base/static/js/models/model-utils.js
- src/base/static/js/routes.js
- src/base/static/js/utils.js
- src/base/static/js/views/app-view.js
- src/base/static/js/views/layer-view.js
- src/flavors/duwamish_flavor/config.yml
Addresses: #527, #549 
This PR is a major refactor of the code that loads places and landmarks. Changes include:
- Support for places with landmark-style urls. If a place model has a field called `url-title`, the value of this field will correspond to the place's url in the app. The underlying Shareabouts-style url will not be used.
- Reduced code duplication and complexity in the AppView. We now have a single `viewPlaceOrLandmark()` method, which accommodates loading from traditional place urls (`report/342`), landmark urls (`/landmark`), and places with landmark-style urls.
- Slight loading performance boost on direct url loads. We might experience quicker load times when we load the app directly to a place or landmark url.
> Refactor place/landmark loading; support landmark-style urls

- src/base/jstemplates/place-detail-promotion-bar.html
- src/base/static/scss/_content.scss
- src/base/static/scss/_forms.scss
- src/flavors/duwamish_flavor/config.yml
Addresses: #665.
Detail view styling changes made to the base project:
* Tighten line spacing in detail view headers
* Remove "Further description" prompt from restoration and vision detail views
* In story mode, place promotion bar controls on a single line; leave them on two lines otherwise
* Fix an issue with incorrectly configured linestring style info
> Detail view design changes

- src/base/static/js/views/place-list-view.js
Addresses #679.
I think this bug stemmed from the fact that as we iterated through un-rendered models in the list view to apply filtering criteria, we modified the underlying object we iterated over:
https://github.com/mapseed/platform/blob/master/src/base/static/js/views/place-list-view.js#L259-L298
Instead, we should wait until the iteration is complete to `.remove()` models from `this.unrenderedItems`.
> fix list filtering bug

- README.md
Very open to suggestions/feedback on this. I'm attempting to follow [the standard-readme spec](https://github.com/RichardLitt/standard-readme/blob/master/spec.md), which I think gives good structure. Of note is how much more focused this `README` is on users, as opposed to contributors.
A few things to note:
- I used our already-existing short description "Community powered mapping for environmental health, starting with our most polluted rivers" although with the Mapseed name we seem to have outgrown it.
- We also need to change our Github repo description to match the short description.
- I listed @LukeSwart and @futuresoup as maintainers, but I wasn't sure.
- Our [license](https://github.com/mapseed/platform/blob/master/LICENSE.txt) appears to be an unchanged holdover from Shareabouts, …
> Rewrite README for standard-readme compliance

- src/base/jstemplates/gis-legend-content.html
- src/base/static/js/views/app-view.js
- src/base/static/js/views/gis-legend-view.js
- src/base/static/js/views/map-view.js
Addresses: #557, #612.
This PR makes it possible to group multiple layers under one visibility checkbox in the sidebar panel. Any layer types can be arbitrarily grouped together: Shareabouts place layers, third-party GeoJSON, esri, KML, etc.
To group layers, use the `constituentLayers` key in the sidebar section of the config. For example, to group the `restoration` and `vision` layers together, remove the individual entries for `restoration` and `vision` and add the following:
```
- id: vision_and_restoration
title: _(Vision and Restoration Sites)
visibleDefault: true
constituentLayers:
- vision
- restoration
```
> Support multiple datasets per layer

- src/base/static/js/views/map-view.js
- src/base/static/libs/leaflet-wmts.js
- src/base/templates/base.html
This PR adds support for WMTS layers (an optimized version of WMS layers) via a [small plugin](https://github.com/mylen/leaflet.TileLayer.WMTS) and a new layer type setting.
Use `type: wmts` in the layer config to declare a WMTS layer.
> add WMTS support

- src/base/static/js/routes.js
Because the viewLandmark route handler was not included on the list of routes that don't require a clear of the location type filter, we were running unnecessary filter clearing logic in routes.js and in place-list-view.js whenever a landmark (or a landmark-as-place) was clicked on.
This commit adds viewLandmark to the list of routes that don't require filter clearing.
> Fix a performance bottleneck related to filtering

- src/base/static/js/views/app-view.js
- src/base/static/js/views/map-view.js
Apparently we missed a bit of filtering logic in the multidataset
refactor. This commit corrects the omission. It also adds a call to
hidePanel() when closing the content panel on maps with active
location_type filters. Previously, the content panel wouldn't close
in this situation.
> Update filtering logic

- src/base/static/js/views/layer-view.js
- src/base/static/libs/leaflet.argo.js
- src/base/static/libs/static-parser.js
- src/base/templates/base.html
- src/flavors/bogtobay/config.yml
- src/flavors/central-puget-sound/config.yml
- src/flavors/defaultflavor/config.yml
- src/flavors/duwamish-watershed/config.yml
- src/flavors/duwamish_flavor/config.yml
- src/flavors/greensboropb/config.yml
- src/flavors/greenways/config.yml
- src/flavors/gtopenspace/config.yml
- src/flavors/lakewashington/config.yml
- src/flavors/pboakland/config.yml
- src/flavors/pugetsound/config.yml
- src/flavors/rail/config.yml
- src/flavors/raingardens/config.yml
- src/flavors/snoqualmie/config.yml
- src/flavors/trees/config.yml
- src/flavors/waterfront/config.yml
- src/flavors/willamette/config.yml
Addresses: #704.
**This PR needs to be carefully tested on each flavor before merging**, as it introduces changes in the way zoom and style rules are handled.
Improve layer view performance by reducing unnecessary and duplicated work spent evaluating zoom and style rules.
- evaluate style rules for visible layers only
- draw newly visible geometry on `moveend`, not `move`
- cache style rules on layer views as functions
Caching style rules as functions eliminates not only the need for `eval` statements for layer views, but for their static parse replacement as well. Instead, we cache style and zoom rules on layer views as functions we can call later, using `new Function()`.
Note that we retain the `L.argo` style and zoom rule evaluation functionality. This is to support json and ESRI …
> Optimize layer view performance

- src/base/jstemplates/place-form-field-types.html
- src/base/static/js/models/model-utils.js
- src/base/static/js/views/app-view.js
- src/base/static/js/views/map-view.js
- src/base/templates/base.html
Addresses: #466 
This PR bumps us up to Leaflet 1.0.3. 
For flavors which use Carto, we replace `cartodb.js` with `cartodb_noleaflet.js` and a separate load of Leaflet itself. This is to work around the fact that Carto has apparently not migrated all Leaflet 1.0 features yet.
This PR also adds the ability to use Leaflet's `flyTo` method on story points. Set the following flag in a story point's config to use `flyTo`:
```
flyTo: true
```
**NOTE:** Some testing has revealed that `flyTo` does not work well on Carto layers, causing some pretty nasty-looking errors. So although we can combine Carto and standalone Leaflet 1.0.3 on the same map, we should avoid setting the `flyTo: true` flag on story points that contain Carto layers.
> Upgrade to Leaflet 1.0.3

- src/base/static/js/views/app-view.js
This PR reverts changes introduced in #622, which placed a call to `invalidateSize()` inside a very short timeout in an effort to defeat the off-center bug that sometimes causes the map to center incorrectly on a selected place.
But as @LukeSwart originally noted in #622, using a timeout in this way is hacky and not a great idea. There have been cases where the timeout causes the centerpoint of the map to wander around, and with the spotlight visible it's really apparent that something weird is happening.
I think the map is actually more usable without this hack in the code. We might still encounter the off-center bug from time to time, but perhaps we can think of another less fragile way to counteract that behavior down the road.
> Revert use of invalidateSize() inside a timeout

- src/base/static/js/models/attachment-model.js
- src/base/static/js/models/place-model.js
- src/base/static/js/views/layer-view.js
- src/base/static/js/views/place-form-view.js
- src/base/static/js/views/rich-text-editor-view.js
**WAIT TO MERGE--NEEDS ANOTHER ROUND OF TESTING**
This PR fixes an issue with embedded images added via the Quill rich text editor in the dynamic form. 
Previously, when embedding images in the dynamic form, we persisted data urls of those images to the server. Now, we make sure to save all embedded images first (as attachment models), then replace any rich text content data urls with their corresponding S3 bucket urls, then re-save the host place model with any rich text `<img>` tags set to their S3 source.
> Embedded image uploads in the dynamic form

- src/base/static/js/views/layer-view.js
Layer view optimizations apparently broke the ability to hide places via the editor. This PR fixes the issue.
> fix an issue with the "Remove this post" button in the editor

- src/base/static/js/views/geometry-editor-view.js
- src/base/static/js/views/place-detail-view.js
- src/base/static/js/views/place-form-view.js
- src/base/static/scss/_buttons.scss
- src/base/static/scss/_content.scss
- src/base/static/scss/_forms.scss
- src/base/static/scss/_media.scss
- set background color of editor toolbars to charcoal gray
- after clicking Create Marker on the form, place a marker on the map at the centerpoint and jump immediately into editing mode
- fix the height of Quill-inserted iframes (to prevent strange dimensions on embedded videos)
- make save/delete toolbar and Quill toolbars stick to the top of place detail views when scrolling down
- make the Quill toolbar stick to the top of the place form view when scrolling down
> Editor UI and usability updates

- src/base/static/js/models/model-utils.js
- src/base/static/js/views/app-view.js
- src/base/static/js/views/map-view.js
- src/base/templates/base.html
This PR reverts changes introduced in #739.
There are too many weird interactions between Leaflet 1.0.x and CartoDB 3.15.x (i.e. flickering map tiles, inexplicably absent features).
For now, it's better to use an older version of Leaflet with Carto.
> Revert to Leaflet 0.7.5

- src/base/jstemplates/gis-legend-content.html
- src/base/jstemplates/layer-info-window.html
- src/base/static/js/views/gis-legend-view.js
- src/base/static/js/views/layer-info-window-view.js
- src/base/static/js/views/sidebar-view.js
- src/base/static/scss/_legend.scss
- src/base/static/scss/_map.scss
- src/base/static/scss/_media.scss
- src/base/templates/base.html
- src/flavors/central-puget-sound/config.yml
- src/flavors/central-puget-sound/static/css/custom.css
This PR makes the following changes to the layers panel:
- remove checkboxes and radio buttons
- add new hover and selected styling for individual layers
- tweak spacing and lettering
- add the option of displaying an icon next to each layer in the layer panel which, when clicked, opens a popup with information about the layer.
- Use the `info:` flag in the `sidebar` section of the config to define the content that appears in popups.
> Layer panel improvements

- src/base/static/js/utils.js
- src/base/static/js/views/place-detail-view.js
- src/base/static/js/views/place-form-view.js
Addresses: #764 
This PR adds the ability to set admin permissions on a `location_type`-by-`location_type` basis within a given dataset.
To set permissions for an individual `location_type`:
1. In the Django admin panel, create as many dataset groups (each with a unique name) as needed. Add social auths to groups as appropriate. Remember to grant `retrieve`, `create`, `update`, and `destroy` privileges for each group.
2. In the dynamic form section of the config, add an `admin_groups` array to each category config that you want to grant group privileges to. This array should list, by name, all the groups that have admin privileges for the given category. For example:
```
place_detail:
- category: featured_place
admin_only: true
includeOnForm: true
admin_groups:
- approved_editors
- …
```
> support admin permissions by location_type

- src/base/jstemplates/place-detail.html
- src/flavors/central-puget-sound/config.yml
This is a simple feature that lets us hide an individual form field from the detail view on which it would otherwise appear.
This is different from the existing `private-` field functionality, which prevents data of this type from ever being sent to the client at all. Hidden fields are sent to the client (and thus can be edited in editor mode), but are not visible on rendered place detail views.
Add a `hideFromDetailView: true` flag to a field config to enable this behavior.
> add option for selectively hiding form fields on place detail views

- src/base/static/js/views/filter-menu-view.js
- src/base/static/js/views/sidebar-view.js
- src/flavors/central-puget-sound/config.yml
Previously, the filter-menu-view created a filter for every `location_type` in the `place_detail` section of the config. This PR allows for a custom filter list that overrides this default behavior.
Set up a custom filter list as follows:
```
- id: filters
title: _(Report Filters)
view: FilterMenuView
icon: filter
active_filters:
- category: conserve-water
icon_url: /static/css/images/markers/marker-conserve-water.png
label: _(Conserve Water)
...
```
If no `active_filters` list is supplied, the default behavior will apply: a filter for every `location_type` found in the `place_detail` section of the config will be created.
Note that even if a `location_type` is not listed in the filter menu, map points of that `location_type` will still be affected by filter selections. This means that if …
> Make filter list configurable

- package.json
- src/base/jstemplates/place-form-field-types.html
- src/base/static/js/utils.js
- src/base/static/js/views/place-form-view.js
- src/base/static/scss/_forms.scss
- src/flavors/central-puget-sound/config.yml
This PR adds the ability to create autocomplete combobox dropdown fields on the dynamic form. Use the `type: dropdown-autocomplete` flag to create an autocomplete field.
Following suggestions in [this issue](https://github.com/mapseed/platform/issues/781), we have a fork of the [alphagov/accessible-autocomplete module](https://github.com/alphagov/accessible-autocomplete) with [minor modifications](https://github.com/mapseed/accessible-autocomplete/pull/1) for our own purposes.
> Add combobox autocomplete feature

- README.md
- package.json
I notice new contributors are having issues using outdated versions of npm/node when setting up their environments. This PR addresses this problem.
> Add node versions 

- src/base/static/js/utils.js
- src/base/static/js/views/place-form-view.js
- src/flavors/bogtobay/config.yml
- src/flavors/central-puget-sound/config.yml
- src/flavors/defaultflavor/config.yml
- src/flavors/duwamish_flavor/config.yml
- src/flavors/greensboropb/config.yml
- src/flavors/greenways/config.yml
- src/flavors/gtopenspace/config.yml
- src/flavors/lakewashington/config.yml
- src/flavors/pboakland/config.yml
- src/flavors/pugetsound/config.yml
- src/flavors/rail/config.yml
- src/flavors/raingardens/config.yml
- src/flavors/snoqualmie/config.yml
- src/flavors/trees/config.yml
- src/flavors/waterfront/config.yml
- src/flavors/willamette/config.yml
Addresses: #784
Previously all form fields listed under the `common_form_elements` section of the config were automatically placed at the end of every form type. This commit allows arbitrary placement of common_form_elements within a given form config.
Note that this PR changes the way the `common_form_elements` section of the config works. Fields are now listed by key, e.g.:
```
common_form_elements:
address:
type: geocoding
prompt: _(Your address:)
placeholder: _(Address)
optional: true
title:
...
```
To incorporate a common form element, use the `commonFormElement` type in a form config:
```
- name: address
type: commonFormElement
```
The `name` field must match the key used in the `common_form_elements` section of the config.
Also note that common form elements are **no longer …
> Support arbitrary placement of common_form_elements

- src/base/static/js/models/place-model.js
**WAIT TO MERGE**
NOTE: This should be merged once https://github.com/mapseed/api/pull/91 is merged on the api. That PR enables pre-flight OPTIONS requests to return an appropriately scoped `Access-Control-Allow-Origin` header, enabling cross-origin ajax with credentials.
Now that we don't have a proxy server to attach cookies and forward them to the api, we need to allow the browser to send  cross-origin credentials (which includes cookies) to support session-based authentication. The proxy previously attached the `sessionid` cookie [here](https://github.com/mapseed/platform/blob/master/src/base/views.py#L397-L407).
See: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
Note that until this PR is merged, all post submission and editor functionality is …
> Support CORS ajax requests with credentials

- src/base/static/js/views/app-view.js
- src/flavors/central-puget-sound/config.yml
Addresses #812 
Add the ability to configure the basemap when the "Add A Report" button is clicked.
Usage:
In the `place` section of the config add a `default_basemap` flag that references the id of the desired basemap layer. For example:
```
default_basemap: satellite
```
> Add option to configure basemap used during reporting

- src/base/static/js/views/map-view.js
- src/flavors/central-puget-sound/config.yml
Addresses: #804 
Add per-basemap max zoom settings. If a basemap defines a max zoom that is less than the universal max zoom (set in `config.map.options.maxZoom`), the map will use this custom max zoom setting while the given basemap is active.
Upon basemap change, if the user was zoomed in farther than the zoom extent allowed by a basemap's custom zoom settings, the map will zoom out to the max zoom allowed by the basemap.
To set a basemap custom max zoom level, add a `maxZoom` flag to the `layer` config, e.g.:
```
- id: topo
type: basemap
url: //{s}.tile.stamen.com/terrain/{z}/{x}/{y}.png
maxZoom: 13
```
> Add option to limit max zoom by basemap layer

- build-utils/config-loader.js
- build-utils/config-template.hbs
- package-lock.json
- package.json
- src/base/templates/base.hbs
- static-build.js
- webpack.config.js
Addresses: #802 
This PR adds a custom webpack loader which will watch and rebuild changes made to the config during development. The loader will only rebuild the config in English; localization is not supported. To test localization for a given language, it will be necessary to run a production build:
```
npm run build
```
Alternatively, to run a production build and also start the dev server (which is probably more useful):
```
NODE_ENV=production npm start
```
> Static site: watch and rebuild config automatically during development

- src/flavors/central-puget-sound/config.yml
- src/flavors/central-puget-sound/jstemplates/place-detail.html
- src/flavors/central-puget-sound/static/js/views/place-form-view.js
This is implemented as flavor-specific code since co-mingling attachment buttons and rich text image embeds is a little convoluted. This is something that we can rethink during the react port, but for now this is the easiest way to get a cover image button into mywater.world.
> add cover image attachment button to mywater flavor

- package.json
- src/base/templates/base.hbs
I discovered that we're not using webpack dev server as intended: in development we've been serving bundles from the filesystem, but instead we should be serving dev server's in-memory bundles. This PR fixes that.
Doing so significantly improves incremental build times and serve time.
Overall, though, incremental build times are still on the slow side (5-10 seconds). I'm hoping that as we finish up the React port the overall project will simplify and build times will improve.
> Improve dev server and incremental dev build performance

- package-lock.json
- package.json
Long-term, we should either publish our fork on npm, or send a PR get the changes from our fork into upstream.
For now, this PR locks the dep to a hash to ensure we are referencing the intended "release" of our forked package.
> chore(package.json) lock package fork to git commit hash

- .eslintrc
- .gitignore
**eslint**:
* don't check for indentation (Prettier should do that)
**gitignore**:
* ignore `.swp` files
> chore: update eslintrc and gitignore

- .prettierrc
- package.json
From what I can tell the only default setting we override is `trailingComma: all`. Does that sound right?
> Add prettierrc

- src/base/static/js/views/map-view.js
- src/base/static/libs/leaflet.argo.js
Add the following enhancements to our marker cluster feature:
* clustering for geojson layers
* enable per-layer clustering (clustering was previously all or nothing)
To cluster individual layer(s), list the layer ids under the `layers` property of the `cluster` section of the config, e.g.:
```
cluster:
layers:
- cso
- input
animate: true
animateAddingMarkers: false
showCoverageOnHover: true
spiderfyOnMaxZoom: true
spiderfyDistanceMultiplier: 1.5
spiderLegPolylineOptions:
opacity: 0
```
Clustering will behave as follows:
* If a `cluster` config is present with no `layers` property, all layers will cluster.
* If a `layers` property is present, only the layers listed there will cluster.
* If no `cluster` config is present, no layers will cluster.
> Cluster enhancements

- .babelrc
- package-lock.json
- package.json
Here is a rolling, updated list of the browsers that we can now support: http://browserl.ist/?q=last+2+versions
> feat(.babelrc) use babel-preset-env as build target

- src/base/static/components/form-fields/form-field.js
Fixes: #910 
Fix a subtle bug that causes rich textarea fields to initialize incorrectly in the place detail editor. The bug was caused by the fact that field type components were mounting with the initial value set by their state-managing grandparents; the "initialization" logic in `FormField` actually caused the *second* render of the field type component. 
In most cases this behavior didn't cause a problem. But in the cause of rich textarea fields, the initial field value might need to be transformed in order to swap rich text markup with `<img>` tags of the image content itself. Thus it was possible for rich textarea fields to render with the markup in place.
To fix this, we prevent mounting of field type components until after `FormField` has had a chance to trigger its field …
> Fix form field init bug

- package-lock.json
- package.json
- webpack.config.js
We were having some issues with CSS rules bundling in the wrong order (custom css was getting bundled before base project css). This might have started happening when we updated webpack or it might have been an issue all along and we just got around it with `!important` flags in the custom css.
In any case, based on [this](https://github.com/webpack/webpack/issues/215) thread, it sounds like updating the `extract-text-webpack-plugin` fixes issues with css bundle order.
Also remove a couple of unused css files from the bundle.
> chore(webpack): update extract-text-webpack-plugin to 3.0.2

- package-lock.json
- package.json
- webpack.config.js
A few optimizations to our production build:
* remove the redundant Uglify plugin (the `-p` flag to webpack accomplishes the same thing)
* use `DefinePlugin` to make sure the `NODE_ENV` variable is correctly received by packages (see [here](https://webpack.js.org/guides/production/))
* switch off `devtool` on production builds. Somehow the `devtool` setting affects production, which is weird
These optimizations cut the bundle size almost in half.
> optimize production bundle

- __mocks__/config-mock.js
- jest.config.js
- scripts/config-loader.js
- scripts/static-build.js
- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/form-field.js
- src/base/static/components/form-fields/types/geocoding-field.js
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/__tests__/input-form.test.js
- src/base/static/components/input-form/form-category-menu-wrapper.js
- src/base/static/components/input-form/index.js
- src/base/static/components/input-form/input-form-category-button.js
- src/base/static/components/input-form/input-form-category-selector.js
- src/base/static/components/place-detail/index.js
- src/base/static/components/place-detail/metadata-bar.js
- src/base/static/components/place-detail/place-detail-editor.js
- src/base/static/components/place-detail/promotion-bar.js
- src/base/static/components/place-detail/survey-response-editor.js
- src/base/static/components/place-detail/survey-response.js
- src/base/static/components/place-detail/survey.js
- src/base/static/components/ui-elements/submitter-name.js
- src/base/static/components/ui-elements/support-button.js
- src/base/static/js/views/app-view.js
- src/base/static/utils/common-form-elements.js
- src/base/static/utils/config-utils.js
- webpack.config.js
Just your everyday importable config singleton. Nothing fancy.
Convert the `config.yml` object to an importable module. This eliminates the need to pass the config object through layers of component props.
Note that the config is still injected into the Backbone entry point and passed around as usual. For the time being we'll have two copies of the config object: one for use by Backbone, and one for use by React.
**TODO**
> Importable config singleton

- src/base/static/components/molecules/story-chapter.scss
- src/base/static/components/story-sidebar/index.js
- src/base/static/utils/collection-utils.js
- src/base/static/utils/story-utils.js
The story sidebar will refuse to load if any chapter contains an incorrect url or a url that doesn't exist in any collection. This PR makes the sidebar robust to these misconfigurations.
Also fix an issue with story chapter content overflowing its container.
> refactor: make story abstraction robust to misconfigurations

- src/base/static/components/form-fields/form-field.js
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/__tests__/input-form.test.js
- src/base/static/components/input-form/index.js
- src/base/static/constants.js
- src/flavors/defaultflavor/config.yml
- src/flavors/snohomish/config.yml
- src/flavors/snohomish/static/css/custom.css
Addresses: #933.
Add basic form field visibility triggering, i.e. the ability for one field to trigger the visibility of other fields. Also add the option to make fields hidden by default.
The config footprint for this is as follows:
```
fields:
- name: dog_owner
type: big_radio
prompt: _(Do you own a dog?)
content:
- label: _(Yes)
value: yes
- label: _(No)
value: no
trigger:
trigger_value: yes
targets:
- dog_name
- dog_age
- name: dog_name
type: text
prompt: _(My dog's name is:)
hidden_default: true
- name: dog_age
type: text
prompt: _(My dog's age is:)
hidden_default: true
```
> Add basic form field visibility triggering

- src/base/static/js/views/app-view.js
The map off-center bug persists, and seems to have gotten worse with the introduction of more React components. I think the root of the problem lies in the way overall layout of the page is handled (i.e. hanging classes off the `body` tag) and we'll try to rethink that system in a bit when we finish rebuilding the application.
For now, though, this PR seems to improve things, although is a little hacky.
> fix: another fix for the off-center bug

- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/types/input-form-submit-button.js
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/index.js
- src/base/static/components/place-detail/survey.js
It was previously possible to submit forms in Mapseed by pressing the enter key on certain fields (like text fields).
This is undesirable, since we want submissions to occur only via the Submit button.
This PR disables enter submissions on the input form and the place detail survey form.
> Prevent the enter button from submitting forms

- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/types/index.js
- src/base/static/components/form-fields/types/informational-html-field.js
- src/base/static/constants.js
- src/base/static/utils/field-response-filter.js
- src/flavors/defaultflavor/config.yml
Add a form "field" intended to display arbitrary HTML content. Use as follows:
```
- name: info
type: informational_html
prompt: _(Some information:)
content: <div>Any HTML string</div>
```
Contents of this field will not be submitted to the database and will not appear on detail views.
> feat: add an information-only field type

- src/base/static/components/place-detail/index.js
- src/base/static/js/utils.js
- src/flavors/defaultflavor/config.yml
This PR is a companion to https://github.com/mapseed/api/pull/118 and should be merged at the same time.
Add the ability for logged-in users to edit places they previously submitted under the same user credentials. Submitter editors are presented with the same editor tools as administrators.
Submitter editing can be controlled at the `location_type` level. Submitter editing is disabled by default. To enable it, add the following flag under the `place_detail` section for a given `location_type` in the config:
```
submitter_editing_supported: true
```
> Support submitter editing on detail views

- .babelrc
- .eslintrc
- package-lock.json
- package.json
- src/base/static/client/mapseed-api-client.js
- src/base/static/components/story-sidebar/index.js
- src/base/static/js/views/app-view.js
- src/base/static/state/ducks/config.js
- src/base/static/state/ducks/ui.js
- src/base/static/state/reducers.js
- src/base/static/utils/collection-utils.js
- src/base/static/utils/story-utils.js
- src/flavors/augusta/static/js/views/app-view.js
- src/flavors/hull/static/js/views/app-view.js
- src/flavors/manzanares/static/js/views/app-view.js
- src/flavors/williams/static/js/views/app-view.js
This PR:
- Adds Redux as a dep, and stores our Config data in the store. Uses the "ducks" pattern as described here: https://github.com/erikras/ducks-modular-redux
- Updates StorySidebar to read config data from the Redux store instead of from the Config singleton. 
- Implements a MapseedApiClient to clean up the logic in AppView
- Adds async/await support via Babel
TODO:
> Move Config into Redux store

- package-lock.json
- package.json
- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/response-field.js
- src/base/static/components/form-fields/types/datetime-field-response.js
- src/base/static/components/form-fields/types/datetime-field.js
- src/base/static/components/form-fields/types/datetime-field.scss
- src/base/static/components/place-detail/snohomish-field-summary.js
- src/base/static/constants.js
- src/flavors/defaultflavor/config.yml
- src/flavors/snohomish/config.yml
- src/flavors/snohomish/static/css/custom.css
- webpack.config.js
Updates to the datepicker field.
* convert the datepicker input from a text field to a button. This removes the need for complex validation logic by preventing the user from entering dates in arbitrary formats.
* add a placeholder text option. Set it with the `placeholder` property in the config.
* replace `react-datepicker` with [`react-datetime`](https://www.npmjs.com/package/react-datetime). `react-datetime` is more flexible.
* add optional timepicker. The timepicker defaults to being off; use the `time_format` config property to set a time format (using moment's format strings), e.g.: `time_format: "HH:mm:ss"`
* set the date format with the `date_format` property, e.g.: `date_format: "YYYY-MM"`. Leave out any configuration for days to create a month and year picker.
* set the display …
> Improve datepicker field

- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/form-field.js
- src/base/static/components/form-fields/types/datetime-field.js
- src/base/static/components/form-fields/types/datetime-field.scss
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/index.js
- src/base/static/constants.js
- src/base/static/js/views/app-view.js
- src/base/static/js/views/map-view.js
- src/base/static/stylesheets/themes/default-theme/variables.scss
- src/flavors/snohomish/static/css/custom.css
* Center the map on click
* Open the sidebar on route to a story chapter
* Change look of datetime fields from a button to a text input
* Disallow manual entry in datetime fields
* When triggering the visibility of one or more fields, allow for the option to auto-focus the first of the triggered fields
* Open the datepicker field on focus (not just on click). Note that as of this PR no other field types are configured to do anything when auto-focused.
* combined with the feature above, the Snohomish flavor datepicker fields will now auto-open after selecting an action.
> Map and form enhancements

- src/base/static/components/form-fields/types/big-checkbox-field.scss
- src/base/static/components/form-fields/types/big-radio-field.scss
- src/base/static/components/form-fields/types/big-toggle-field.scss
Checkboxes, radio fields, and toggles have a CSS `:hover` style that works incorrectly on touch devices: When a checkbox, etc. is checked and then un-checked, the hover style lingers until another touch event occurs.
This PR uses a CSS feature query to ignore the `:hover` styling on devices that don't support it.
> Fix lingering hover styling for checkboxes on touch devices

- .eslintrc
- scripts/static-build.js
- src/base/static/components/form-fields/types/datetime-field.js
- src/base/static/js/routes.js
- src/base/templates/base.hbs
- src/flavors/snohomish/config.yml
- src/flavors/snohomish/jstemplates/pages-nav.html
- src/flavors/snohomish/static/css/custom.css
- src/flavors/snohomish/static/js/views/app-view.js
- src/flavors/snohomish/static/js/views/sidebar-view.js
**IN PROGRESS**
* Close datetime picker on select
* Add google analytics tracking for client-side routing
* To enable analytics tracking for a given flavor, you need to have a `.env` key that follows this pattern: `<FLAVOR>_GOOGLE_ANALYTICS_ID=UA-XXXXX-Y`, where `UA-XXXXX-Y` is the Google Analytics id. For example, to enable analytics tracking for the `snohomish` flavor: `SNOHOMISH_GOOGLE_ANALYTICS_ID=UA-12345-6`
* Add layer panel toggle in header
* Design tweaks
> Snohomish flavor tweaks

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
- src/flavors/defaultflavor/config.yml
To enable, set the `geolocation_enabled: true` flag in the `map` section of the config. Note that the `geolocation_onload` and `geocode_bounding_box` parameters have been removed and will no longer do anything.
Clustering must be enabled on a layer-by-layer basis. Clustering is supported for any GeoJSON `Point` layer (including Mapseed place layers). Note that if you enable clustering on a layer with mixed geometry, non-`Point` features will be hidden.
To enable clustering for a layer, add the following to the layer's config:
```
cluster:
is_enabled: true
cluster_max_zoom: 14
cluster_radius: 200
paint:
circle-color: "#caffca"
circle-radius: 30
```
Cluster `paint` properties support step expressions for controlling cluster size, color, etc. based on number of points clustered. See: …
> [Port map] Add geolocation and clustering

- src/base/static/components/form-fields/form-field.js
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/index.js
- src/base/static/constants.js
- src/flavors/snohomish/config.yml
- src/flavors/snohomish/static/css/custom.css
On multi-stage forms, add the ability for form fields to trigger stage advance on a certain field value. The immediate use case is to support the `snohomish` flavor.
To use this feature, add the following flag to a field config:
```
advance_stage_on_value: <value>
```
where `<value>` is one of the possible values of the field.
Note that this feature *must* be used on a multi-stage form. Also note that this feature won't work with checkboxes (because checkbox values are stored during runtime as immutable lists). Further refactoring could address this issue, but the priority is low so I'm not going to worry about it for now.
> feat: form fields that trigger stage advance

- package-lock.json
- package.json
- src/base/static/js/views/app-view.js
Add the [browser-update](https://www.npmjs.com/package/browser-update) plugin to notify users with old browsers that they need to upgrade.
Current minimum versions are as follows:
* Edge: last 2 versions
* IE: >= 11
* Firefox: last 2 versions
* Safari: last 2 versions
* Chrome: last 2 versions
These versions have been tested with the Snohomish production flavor via [browserling](https://www.browserling.com/) (and in the case of Safari 10 via my personal machine).
Question: These versions are somewhat arbitrary-- would it be better to have a policy like "last 2 versions" instead?
> Add browser update plugin

- src/base/static/components/atoms/input.js
- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/types/datetime-field.js
- src/base/static/components/form-fields/types/datetime-field.scss
- src/flavors/snohomish/config.yml
- src/flavors/snohomish/static/css/custom.css
Add an optional "ongoing" checkbox to the datepicker input field. Update `snohomish` flavor to use this feature.
To enable the ongoing option, add the following line to the config for a `datetime` field:
```
ongoing_label: _(Label for ongoing checkbox)
```
If the `ongoing_label` attribute is not present, the ongoing option will not be displayed.
The UI looks like this:
Date entry and "ongoing" entry are mutually exclusive: if the "ongoing" checkbox is selected, any date entered in the date field is cleared. If a date is entered, the "ongoing" checkbox is unselected.
A special far-future date (`9999-12-31 23:59:59`) is used to represent an ongoing date selection in the database.
> Add ongoing option to datepicker field

- .modernizrrc.js
- package-lock.json
- package.json
- src/base/static/components/form-fields/types/big-checkbox-field.js
- src/base/static/components/form-fields/types/big-checkbox-field.scss
- src/base/static/components/form-fields/types/big-radio-field.js
- src/base/static/components/form-fields/types/big-radio-field.scss
- src/base/static/components/form-fields/types/big-toggle-field.js
- src/base/static/components/form-fields/types/big-toggle-field.scss
- src/base/static/components/form-fields/types/datetime-field.js
- src/base/static/components/form-fields/types/datetime-field.scss
- src/base/static/stylesheets/themes/default-theme/variables.scss
- src/base/static/utils/misc-utils.js
- src/flavors/snohomish/static/css/custom.css
- webpack.config.js
Closes: https://github.com/jalMogo/mgmt/issues/39
Fix a bug where the hover icon on radio, checkbox, and toggle form fields does not appear in Firefox. The bug was caused by a CSS4 feature (media feature queries to detect the presence of a touch device) not yet supported in FF.
Instead of using CSS to detect touch devices we now do so in the javascript.
This PR introduces `Modernizr` to the project (in a very lightweight form just for detecting the presence of touch devices). Detection of touch devices seems nitpicky enough that we want to outsource this to a third-party tool like `Modernizr`.
We use the [`webpack-modernizr-plugin`](https://www.npmjs.com/package/webpack-modernizr-loader) to integrate a lightweight build of `Modernizr` into our bundle.
For background context, the need to …
> Fix toggle/checkbox/radio hover issue

- src/base/static/components/place-detail/metadata-bar.js
- src/base/static/js/routes.js
- src/flavors/augusta/static/js/views/app-view.js
- src/flavors/bathgate/static/js/views/app-view.js
- src/flavors/hull/static/js/views/app-view.js
- src/flavors/manzanares/static/js/views/app-view.js
- src/flavors/williams/static/js/views/app-view.js
The changes made here: https://github.com/mapseed/platform/blob/847a2858e323fbca575b1b04500ccd0e0298430a/src/base/static/js/views/app-view.js#L1032 are causing an error in routes.js, where "AppView is not a constructor". This is because the node modules syntax is affected by the es6 export syntax, that is used in AppView.
This PR fixes that issue. We should be using es6 import syntax for all future development.
This PR also fixes the tests that were broken in this commit: https://github.com/mapseed/platform/commit/d20ba4c0b0dd3ae426cf5334ef51773631fbcb76
> Fix broken AppView import and tests

- src/flavors/central-puget-sound/static/js/views/app-view.js
- src/flavors/pugetsound/static/js/views/app-view.js
- src/flavors/snohomish/static/js/views/app-view.js
Since AppView was refactored to use the es6 module syntax, it was causing the CPS, PugetSound, and Snohomish flavors builds to fail. This PR fixes those import errors. 
I believe the equivalent fix using the commonJS syntax would be something like this:
```javascript
const AppView = require("../../../../../base/static/js/views/app-view.js").default;
```
but moving forward, we should avoid using the commonJS syntax and start using the es6 module syntax.
> fix(AppView): import errors related to mixing es6 and commonjs module syntax

- src/base/static/js/models/attachment-model.js
- src/base/static/js/models/place-model.js
- src/base/static/js/models/submission-collection.js
- src/base/static/js/models/submission-model.js
Addresses: https://github.com/jalMogo/mgmt/issues/32
Addresses the following, outlined in the issue above:
- Getting a 400 when editing a Place that was submitted by a logged in user
- Getting a 400 when editing a Submission that was submitted by a logged in user
- Getting a 400 when adding/deleting an Attachment as an admin
This PR should be fine to deploy as-is, but to be safe, I think we should deploy it along with the new 1.8 API.
> fixes for django 1.8

- package.json
- scripts/deploy.js
This simplifies the deployment process, so that we can set the `FLAVOR` and `DEPLOY_DOMAIN` env vars in our `.env` file, then run `npm run build-deploy`, to build and deploy our bundle.
ie:
```
FLAVOR=snohomish
DEPLOY_DOMAIN=snohomishcd.mapseed.org
```
Of course, this assumes that `API_ROOT`, `<flavor>SITE_URL`, and other env vars have been correctly set in the `.env` file.
> chore(package.json): add new deploy scripts

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
- src/base/static/utils/collection-utils.js
- src/flavors/defaultflavor/config.yml
This PR elevates the concept of "focused" geometry styles, which has been part of Mapseed/Shareabouts since the beginning, to a first-class member of the layer abstraction.
To do this we introduce a dedicated Mapbox source for focused geometry, we create dedicated Mapbox layers to render that source as needed, and we create a new `focus_styles` section of the layer config to hold styles for focused geometry.
This solves several problems:
* Focused geometry now renders consistently on top of non-focused geometry in the same dataset. Previously there was no way to guarantee that a piece of focused geometry would render on top of its unfocused neighbors.
* Config style rules are (hopefully) simplified by removing an arbitrary and obscure dependence on the `isFocused` geometry attribute to …
> Refactor focused geometry

- scripts/static-build.js
We were missing `spritesheet.json` and `spritesheet.png` in our build files. We were using `spritesheet@1.json` and `spritesheet@1.png` for low-res devices instead; this was apparently wrong, as discussed here: https://www.mapbox.com/mapbox-gl-js/style-spec/#sprite
> Fix spritesheets on low-DPI devices

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
Closes: https://github.com/jalMogo/mgmt/issues/84
Addresses: https://github.com/jalMogo/mgmt/issues/85
Two mobile MapboxGL issues have cropped up:
* Click events are not registered at all on touch devices. It is not possible to click on places and open detail views on mobile devices as far as I can tell.
* `map.easeTo`'s behavior is inconsistent on touch devices, sometimes failing to center on the point it's supposed to.
We fix these issues by:
* Listening for `touchstart` events in addition to `click` events. This allows us to interact with places on touch devices, but I am not at all certain why this change is needed. Mapbox documentation and examples suggest that `click` events should work on touch devices. I'm merging this fix, but this needs more investigation.
* Swapping `easeTo` …
> Quick fixes for issues with clicked-on places on mobile devices

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
Closes: https://github.com/jalMogo/mgmt/issues/90
When deeplinking to a place our initial map state was not being correctly set in Redux. This PR corrects the issue.
> Correctly position map when deeplinking

- src/base/static/libs/maps/mapboxgl-provider.js
Addresses: https://github.com/jalMogo/mgmt/issues/85
Animated MapboxGL transitions (`map.easeTo`, `map.fitBounds`, and `map.flyTo`) work inconsistently on mobile devices (tested on iOS and Android). On mobile devices these methods will very often have no effect at all, but will also produce no error output. The only time they seem to work is on initial page load (for example, if you load directly to a slippy `/z/x/y` route).
This PR  fixes the issue by calling these methods inside a 0-length timeout. I know this is hacky, but this is the only fix I can find for the time being. This feels like a low-level problem perhaps caused by the complex set of dependencies we have in play at the moment. I say that because simple MapboxGL demos do not exhibit this problem when using `easeTo`, …
> Fix animated map transitions on mobile devices

- package-lock.json
- package.json
This should remove the
>We found a potential security vulnerability in one of your dependencies. 
warning on the repo.
> chore(package.json): remove unused static-eval dep

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/abstract-provider.js
- src/base/static/libs/maps/mapboxgl-provider.js
We should be unsubscribing all event listeners when a React component unmounts. This PR does that.
This will allow us to unmount/remount the MainMap component, which isn't being done now, but will be done in the near future as we progress with the React port and port the ListView, for example.
> fix(MainMap): unbind event listeners when component unmounts

- scripts/deploy.js
Silly mistake-- we were using a separate `params` block to add the `ContentEncoding` header to gzipped index files, which clobbered the previously-set `CacheControl` param. As a result `index.html` files were being improperly cached by CloudFront. This PR fixes that.
> fix(deploy.js): don't clobber cache-control header

- src/base/static/components/organisms/main-map.js
Closes: https://github.com/jalMogo/mgmt/issues/106
I'm not sure how this happened, but somehow the filter expression used to identify the model for a clicked-on feature got reversed, such that clicking on a place focuses all other places on the map. This PR fixes that issue.
> fix(MainMap): correct filter expression for focused features

- src/base/static/js/views/app-view.js
Closes: https://github.com/jalMogo/mgmt/issues/109
The call to `$panelContent.scrollTo()` in the `showPanel()` method in `AppView` causes an error in Safari and misalignment of the content panel. I'm not completely sure why, but I thought it would just be easier to remove this legacy code since it isn't doing very much for us, and the `AppView` is getting refactored soon anyway.
> fix(AppView): remove scrollTo logic in showPanel()

- src/base/static/js/models/place-model.js
Closes: https://github.com/jalMogo/mgmt/issues/116
Follows the same pattern for how we handled issues with the `submitter` and `geometry` `Place` model keys post-Django 1.8.
> fix(PlaceModel): omit submission_sets attribute from Place model submissions

- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
- src/flavors/pbdurham/config.yml
Closes: https://github.com/jalMogo/mgmt/issues/102
We've been creating a lot more mapbox layers than we need to, which can be a hit on performance according to [Mapbox best practices](https://www.mapbox.com/help/mapbox-gl-js-performance/#combine-layers). 
This PR introduces two strategies for controlling the number of mapbox layers created:
* allow the config to declare which feature types are expected in a geojson source
* allow the config to declare that drawing is not supported for a given flavor, saving us from instantiating the `mapbox-gl-draw` plugin and the layers it creates to support drawing
> Reduce number of Mapbox layers needed to render geojson sources

- src/base/static/libs/maps/mapboxgl-provider.js
- src/flavors/defaultflavor/config.yml
Closes: https://github.com/jalMogo/mgmt/issues/125
Add support for labels on features. Use the `label-layout` and `label-paint` keys to set `layout` and `paint` properties for label layers. If using the `feature_types` key to restrict the types of mapboxl layers generated for a given config layer, add `Layer` to the list of feature types so labels will appear.
Sample config setup:
```
- id: sample-json-b
type: json      
is_visible_default: true
source: "https://raw.githubusercontent.com/mapseed/data/master/scorecard.geojson"
feature_types:
- "Label"
- "Polygon"
rules:
- filter:
- "=="
- - "get" 
- "LID_Checklist_Master_score"
- 5
label-paint:
text-halo-color: "#fff"
text-halo-width: 1
label-layout:
text-field:
- "get"
- "CITYNAME"
text-size: 14
text-allow-overlap: false
text-offset:
- 0 …
```
> feat(mapboxgl-provider): add support for feature labels

- scripts/deploy.js
Closes: https://github.com/jalMogo/mgmt/issues/80
> chore(deploy.js): don't cache spritesheet assets

- src/base/static/state/ducks/map-config.js
- src/base/static/state/ducks/place-config.js
- src/base/static/state/reducers.js
This PR should help us establish a distinction between our "config" ducks and our "ui" ducks.
> refactor(ducks): rename config ducks

- src/base/static/client/mapseed-api-client.js
- src/base/static/components/organisms/main-map.js
- src/base/static/constants.js
- src/base/static/js/views/app-view.js
This PR ports our `PLACE_COLLECTION_LOADED_EVENT` event to a Redux dispatch.
This pattern should simplify our app so that MainMap isn't responsible for listening to events and updating the Redux store.
> fix(MainMap): replace emitter event with redux action

- src/base/static/components/form-fields/types/geocoding-field.js
- src/base/static/components/input-form/__tests__/input-form.test.js
- src/base/static/components/input-form/form-category-menu-wrapper.js
- src/base/static/components/input-form/index.js
- src/base/static/components/input-form/input-form-category-button.js
- src/base/static/components/place-detail/index.js
- src/base/static/components/place-detail/metadata-bar.js
- src/base/static/components/place-detail/place-detail-editor.js
- src/base/static/components/place-detail/survey-response-editor.js
- src/base/static/components/place-detail/survey-response.js
- src/base/static/components/ui-elements/submitter-name.js
- src/base/static/components/ui-elements/support-button.js
- src/base/static/components/vv-input-form/index.js
- src/base/static/js/views/app-view.js
- src/base/static/state/ducks/support-config.js
- src/base/static/state/reducers.js
- src/base/static/utils/config-utils.js
- src/flavors/augusta/static/js/views/app-view.js
- src/flavors/bathgate/static/js/views/app-view.js
- src/flavors/hull/static/js/views/app-view.js
- src/flavors/manzanares/static/js/views/app-view.js
- src/flavors/williams/static/js/views/app-view.js
There were a lot of places in the codebase where we were still importing parts of the config directly (i.e. not going through Redux). As discussed in https://github.com/jalMogo/mgmt/issues/154, this creates problems for the localization system.
This PR cleans up this problem.
> refactor: remove direct imports of config object

- src/base/static/components/organisms/main-map.js
- src/base/static/js/views/app-view.js
Similar to how we handled https://github.com/jalMogo/mgmt/issues/142, we want to distinguish between map `moveend`s that are user-initiated and program-initiated.
Failure to distinguish between these two was manifesting itself as a bug that prevented routing to the default page.
> fix(AppView): fix a regression that prevents routing to the default page

- src/base/static/components/molecules/map-legend-group.js
- src/base/static/components/molecules/map-legend-group.scss
- src/base/static/components/organisms/map-legend-panel.js
- src/base/static/components/templates/right-sidebar.js
Closes: https://github.com/jalMogo/mgmt/issues/162
This PR gives us the ability to load two components into the right sidebar: the `MapLegendPanel` and the `ActivityStream`. This mimics the design of the original `pbgreensboro` flavor.
We also refactor the `MapLegendPanel` to be a styled component.
> Add hybrid activity stream/legend component for the right sidebar

- src/base/static/libs/maps/mapboxgl-provider.js
- src/flavors/defaultflavor/config.yml
Closes: https://github.com/jalMogo/mgmt/issues/172
This PR also normalizes the `internalLayer` terminology used in `mapboxgl-provider.js` to `mapboxLayer`, which is more descriptive.
> fix(mapboxgl-provider): prevent premature layer adds to Mapbox styles

- package-lock.json
The LTS version of Node has been updated to 10.x - this PR moves us over to the `10.13.0` version.
https://nodejs.org/en/
https://www.angularminds.com/blog/article/whats-new-in-node-js-version-10-features-and-improvements.html
> chore(package-lock): upgrade to node 10.13.0

- src/base/static/client/mapseed-api-client.js
- src/base/static/components/organisms/main-map.js
- src/base/static/js/views/app-view.js
- src/base/static/libs/maps/mapboxgl-provider.js
- src/base/static/state/ducks/map.js
This PR straightens out some of the logic between "loading" a layer, and marking it as "visible".
Note that some testing/cleanup may be required for the MapLayerGroup/Selector, so that it is consistent with the new logic.
> refactor(MainMap): decouple isVisible from status

- src/base/static/js/utils.js
- src/base/static/js/views/app-view.js
- src/base/static/state/ducks/places.js
This PR fixes an issue where deeplinked places are not focused. The reason for the issue is that a deeplinked place is loaded with a separate call to the API to fetch that place's model independently of the dataset that it's in.
> fix(PlacesDuck): set places correctly when deeplinking to a place

- src/base/static/components/organisms/site-header.js
This PR creates an internal link around all flavor logos/titles that will return the user to the default map zoom and centerpoint. A couple of users have requested this feature so I thought I'd just bake it into all flavors.
> feat(SiteHeader): return to default map coords on logo/title click

- package-lock.json
Via #1116 a version of the `package-lock.json` file was committed which reverted various registry urls from `https` to `http`. I've encountered this issue at various points as well, and it appears to be a problem with npm: https://npm.community/t/npm-install-downgrading-resolved-packages-from-https-to-http-registry-in-package-lock-json/1818/3.
This PR replaces any `http` protocols with `https` using `sed` as suggested in the link above:
```
sed -i '' 's/http:/https:/g' package-lock.json
```
> chore(package-lock): http to https

- package-lock.json
- package.json
- src/base/static/components/organisms/main-map.js
- src/base/static/libs/maps/mapboxgl-provider.js
This `mapbox-gl` version bump seems to have resolved an issue that forced us to use `touchstart` listeners on mobile devices. We can now use `click` listeners reliably.
> chore(package.json): upgrade to mapbox-gl 0.51.0

- .eslintrc
- package-lock.json
- package.json
- scripts/config-loader.js
- scripts/static-build.js
- src/base/static/components/molecules/place-list-item.js
- src/base/static/components/organisms/site-header.js
- src/base/static/components/place-detail/metadata-bar.js
- src/base/static/components/place-detail/survey-response-editor.js
- src/base/static/components/place-detail/survey-response.js
- src/base/static/components/place-detail/survey.js
- src/base/static/components/templates/dashboard.js
- src/base/static/state/ducks/app-config.js
- src/base/static/utils/config-loader-utils.js
- src/flavors/pbdurham/config.json
This PR renders the dashboard's timeline using the app's timezone. Previously, we've been rendering the dashboard's timeline according to the user's timezone. This isn't ideal because the chart should look the same regardless of the timezone that you are viewing the website from.
Changes are staged on snohomish and durham master.
This PR also includes some refactoring:
- Moved the AppConfig prop type into the AppConfig duck. (previously, we've been spreading the prop types across all of the components)
- Refactor config loader to set default config values if they aren't declared.
> feat(Dashboard): render timeline using the flavor's timezone

- src/base/static/components/form-fields/types/rich-textarea-field.js
In recent testing video embeds are not adopting the proper dimensions and are rendering letterboxed. We used to have some code that worked around this, but we took it out for a reason that I can't remember. 
This PR restores the feature that wraps video embeds in some CSS so they maximize their size and don't appear letterboxed.
See here for an explanation of how this feature works: https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php
> refactor(RichTextareaField): restore fluid video dimensions

- scripts/config-loader.js
- scripts/static-build.js
- src/base/static/components/organisms/site-header.js
- src/base/templates/base.hbs
- src/flavors/argentina/config.json
- src/flavors/bogtobay/config.json
- src/flavors/central-puget-sound/config.json
- src/flavors/pboakland/config.json
- src/flavors/raingardens/config.json
Closes: https://github.com/jalMogo/mgmt/issues/200
We make the following assumptions about flavor languages in the config:
1. If a flavor declares no languages, we build a single `index.html` file in English.
2. If a flavor declares languages, we assume the first language listed is the default language. This language will load with the main `index.html` file. Other languages will be built in `index-xx.html` format, where `xx` represents the language code.
> Allow for non-English default languages

- src/base/static/libs/maps/mapboxgl-provider.js
Owing to a bug in `mapbox-gl-draw` (documented here: https://github.com/mapbox/mapbox-gl-draw/issues/617), this PR disables the draw plugin entirely on touch devices.
This PR fixes an issue where flavors with the drawing plugin enabled prevented touch events from registering, making it impossible to click on places on the map when on a touch device.
> fix(mapboxgl-provider): disable draw plugin on touch devices

- src/base/static/client/mapseed-api-client.js
- src/base/static/components/input-form/index.js
- src/base/static/components/organisms/place-list.js
- src/base/static/components/templates/dashboard.js
- src/base/static/state/ducks/places.js
- src/base/static/utils/place-utils.js
- src/flavors/palouse/config.json
- src/locales/en_US/InputForm.json
- src/locales/es/InputForm.json
Depends on https://github.com/mapseed/api/pull/162.
This PR adds support for private places. Private places are hidden from view on the public-facing parts of the site, but are viewable by users with the proper credentials.
Upon submission of a private place, we route to the `/` route and display a modal box confirming the successful private submission of data.
This PR also adds a private form field for the `palouse` flavor.
Tested on the staging API with the `palouse` flavor.
> Add support for private place submission

- src/flavors/pbdemo/config.json
Update the `pbdemo` flavor such that we pull prod `pdurham` data in read-only format but let the form talk to a separate `pbdemo` dataset with mirrored categories.
> Update pbdemo deployment configuration

- src/base/static/components/form-fields/form-field.js
- src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
- src/base/static/components/input-form/__tests__/input-form.test.js
- src/base/static/components/input-form/index.js
- src/base/static/components/place-detail/editor-bar.js
- src/base/static/components/place-detail/index.js
- src/base/static/components/place-detail/place-detail-editor.js
- src/base/static/state/ducks/user.js
- src/flavors/pbdurham/config.json
This PR adds a way to restrict field visibility to members of a dataset group. It also sets up the `pbdurham` config to leverage this feature.
We also remove several uses of the `constants` object.
TODO
> feat: group-restricted fields

- src/base/static/components/molecules/user-menu.js
- src/base/static/js/views/app-view.js
Fixes 3 regressions:
- offline menu shouldn't rendered when it isn't enabled in the config
- the add place button shouldn't render if the user doesn't have permissions in the config
- private places weren't loading because of user fetch race condition
> Offline menu and add place button fixes

- src/base/static/components/app.js
- src/base/static/components/input-form/index.js
- src/base/static/components/organisms/info-modal.js
- src/base/static/components/organisms/info-modal.scss
- src/base/static/components/place-detail/index.js
- src/base/static/components/place-detail/pbdurham-project-proposal-field-summary.js
- src/base/static/components/place-detail/place-detail-editor.js
- src/base/static/js/routes.js
- src/base/static/state/ducks/ui.js
- src/flavors/pbdurham/config.json
- src/locales/en_US/InputForm.json
- src/locales/en_US/PBDurhamProjectProposalFieldSummary.json
Depends on: https://github.com/mapseed/api/pull/170
This PR introduces a publish/unpublish workflow leveraging our private places feature.
When creating a Place, there are now three scenarios that can occur:
* A non-private Place is created, leading to the normal route-to-detail-view behavior
* A private Place is created by someone *with* `can_access_protected` permissions, leading to the normal route-to-detail-view-behavior accompanied by a modal dialog explaining that even though the submitter can see the private Place's detail view, others will not be able to
* A private Place is created *without* `can_access_protected` permissions, leading to a route-to-root behavior accompanied by a modal dialog confirming the successful submission
We also refactor the `pbdurham` config to add a …
> feat: publish/unpublish workflow

- scripts/deploy.js
- scripts/static-build.js
- src/base/static/js/routes.js
This PR restores gettext-based localizations. Instead of baking the translated gettext-based config content into the various localized index files, we make a fetch call on page load to the appropriate translated config file before duck loading begins.
Technically this means that the "localized" index files are obsolete. This PR keeps them in place, though, just so we can fix the broken translations. At a later step we can modernize the entire localization pipeline.
> Fix gettext translations

- src/base/static/components/form-fields/types/autocomplete-combobox-field.js
The CSS for the `accessible-autocomplete` combobox dropdown fields got removed at some point; this PR restores it.
> fix(autocompleteField): restore proper styling

- package-lock.json
This PR include package-lock.json updates after upgrading to the latest nodejs stable: https://nodejs.org/en/
> chore(package-lock): upgrade npm/nodejs

- src/base/static/components/app.js
- src/base/static/components/form-fields/field-definitions.js
- src/base/static/components/form-fields/types/geocoding-field.js
- src/base/static/components/input-form/form-category-menu-wrapper.js
- src/base/static/components/input-form/index.js
- src/base/static/components/molecules/map-centerpoint.js
- src/base/static/components/molecules/map-layer-panel-section.js
- src/base/static/components/organisms/content-panel.js
- src/base/static/components/organisms/geocode-address-bar.js
- src/base/static/components/organisms/left-sidebar.js
- src/base/static/components/organisms/main-map.js
- src/base/static/components/organisms/map-layer-panel.js
- src/base/static/components/place-detail/index.js
- src/base/static/components/templates/map.js
- src/base/static/index.js
- src/base/static/state/ducks/map.js
- src/flavors/pbdurham/config.json
- webpack.config.js
(This branch is based off of `goldpbear/replace-backbone-router`. I'll treat https://github.com/mapseed/platform/pull/1242 as a feature branch.)
This PR improves overall map performance, including zooming and panning and focused geometry selection, by cutting down on the number of Redux dispatches required.
TODO
> Map performance improvements

- scripts/deploy.js
Closes: https://github.com/jalMogo/mgmt/issues/264
We also add a caching policy for bundle assets of one year.
> chore(deploy.js): rewrite uncompressed bundle requests to compressed equivalents

- src/base/static/components/templates/dashboard.js
- src/flavors/pbdemo/config.json
Fixes for the `pbdemo` flavor dashboard.
Add react router HOC. Also add projects dataset to `pbdemo` dashboard and remove demographics category from the dashboard.
> fix(dashboardTemplate)

- src/base/static/components/app.tsx
- src/base/static/components/organisms/main-map.js
- src/base/static/components/templates/map.tsx
- src/base/static/state/ducks/map.js
Addresses: https://github.com/jalMogo/mgmt/issues/275
> chore(MapTemplate): convert to TS

- src/base/static/client/mapseed-api-client/place.js
- src/base/static/client/pdf-service-client.js
- src/base/static/components/input-form/index.js
- src/base/static/components/templates/report.tsx
- src/base/static/utils/place-utils.js
Depends on: https://github.com/jalMogo/api/pull/10
Closes: https://github.com/jalMogo/mgmt/issues/300
This PR forwards a `token` param found in the querystring on to the request made by the `getPlace` API client method initiated by the `report` template. 
JWT tokens are only forwarded for requests for individual Places (since JWTs are implemented as object permissions on the backend).
> feat(report.tsx): forward jwt token param

- src/base/static/components/app.tsx
- src/base/static/components/organisms/left-sidebar.tsx
Closes: https://github.com/jalMogo/mgmt/issues/325
Up on `kittitas-vsp` staging.
Second attempt to fix momentum scrolling on the `TemplateContainer` and the `LeftSidebar` on touch devices.
Oddly, removing the explicit `position: relative` on the `TemplateContainer` div enables momentum scrolling on the main content area without any other CSS.
But I can't get momentum scrolling to work on the `LeftSidebar` without using the deprecated `-webkit-overflow-scrolling: touch` vendor prefix.
I *think* the reason for this discrepancy might be that the `LeftSidebar` sits inside an absolutely positioned container, but I haven't done thorough testing to confirm that.
Tested on iOS Safari, iOS Chrome, and iOS FF. Haven't tested on Andriod.
> fix: momentum scrolling

- src/base/static/components/organisms/right-sidebar.tsx
- src/base/templates/base.hbs
Fix an issue where the `RightSidebar` container can overflow the height of the template container.
> fix(RightSidebar): include header height in right sidebar height calculation

- src/flavors/kittitas-firewise/config.json
Addresses: https://github.com/jalMogo/mgmt/issues/331
Fixes this crash on the `kittitas-firewise` flavor, but does not resolve the underlying problem.
> fix(kittitas-firewise): viewport transition crash

- src/base/static/components/form-fields/types/big-checkbox-field.scss
- src/base/static/components/form-fields/types/big-radio-field.scss
- src/base/static/components/form-fields/types/big-toggle-field.scss
Font Awesome 5 requires an explicit `font-weight` be set.
> fix: font awesome 5 font weights

- src/base/static/components/app.tsx
A dependabot merge this morning introduced a typing conflict between `i18next` and `react-i18next`. This PR resolves it.
I'm not sure I understand why there is a typing problem though. `initReactI18next` should be a `ThirdPartyModule` from here, right? https://github.com/i18next/react-i18next/blob/master/src/index.d.ts#L14
But without the type casting in this PR I get a TS error.
> fix(App): i18next typing

- package-lock.json
- package.json
- src/base/static/components/app.tsx
- src/base/static/components/atoms/imagery.js
- src/base/static/components/input-form/index.js
- src/base/static/components/molecules/form-field-types/geocoding-field.tsx
- src/base/static/components/molecules/left-sidebar-section.tsx
- src/base/static/components/organisms/dashboard/chart-wrapper.tsx
- src/base/static/components/place-detail/place-detail-editor.js
- src/base/static/state/ducks/dashboard-config.d.ts
- src/flavors/palouse/config.json
Closes: https://github.com/jalMogo/mgmt/issues/360
Add an MVP dashboard chart exporter, using the [`dom-to-image`](https://github.com/tsayen/dom-to-image) library. Charts that are configured to be exportable will render with a download button, which will download the chart to a PNG.
This is an MVP, and there is one significant limitation: The exporter cannot deal with clipped content in a scrollable container. So for now we just have to render charts at fixed heights which accommodate all the chart's content.
I suppose a more sophisticated chart exporter would work with `react-virtualized` to render all virtualized content somehow before exporting to a PNG. I haven't yet looked into how that might work...
> feat: dashboard chart exporter

- src/base/static/components/molecules/left-sidebar-section.tsx
- src/base/static/components/molecules/login-menu.tsx
- src/base/static/components/molecules/login-modal.tsx
- src/base/static/components/molecules/user-menu.tsx
- src/base/static/components/organisms/left-sidebar.tsx
- src/base/static/components/organisms/right-sidebar.tsx
- src/base/static/components/organisms/site-header.tsx
- src/base/static/components/templates/map.tsx
- src/base/static/utils/styled.ts
- src/theme.tsx
Updated login menu:
This is also deployed to Mississippi staging
@goldpbear  lmk what you think 👍
> fix(LoginMenu): styling tweaks

- src/base/static/components/form-fields/form-field.js
- src/base/static/components/input-form/index.js
- src/base/static/constants.js
- src/flavors/columbia/config.json
- src/flavors/defaultflavor/config.json
- src/flavors/garfield/config.json
- src/flavors/garfield/static/css/custom.css
- src/flavors/kittitas-firewise/config.json
- src/flavors/kittitas-vsp/config.json
- src/flavors/palouse/config.json
- src/flavors/snohomish/config.json
- src/flavors/spokane/config.json
**WIP**
Closes: https://github.com/jalMogo/mgmt/issues/362
This PR updates the form field visibility feature in two ways:
* allow fields to trigger different sets of fields based on different response values (including multiple values in the case of checkboxes)
* automatically skip form stages with no visible fields on them
The combination of these two features will allow us to build a form for spokane where the responses to one field question configures which remaining form stages a user will see.
@jalMogo -- note that this PR changes the schema of the `trigger` section of a field config (renamed here to `triggers`). See the diff for what the schema looks like now-- hopefully this isn't too bad to deal with on the backend, or lmk what you think.
TODO
> Input form updates: multiple visibility triggers and skippable form stages

- src/base/static/components/molecules/map-filter-slider.tsx
- src/base/static/state/ducks/map-style.d.ts
- src/base/static/state/ducks/map.d.ts
- src/base/static/state/ducks/map.js
- src/flavors/kittitas-firewise/config.json
- src/flavors/mississippi/config.json
Allows us to configure multiple filter sliders, which will continue to be displayed depending on which layer group is visible.
> feat(FilterSliders): enable multiple filter sliders

- src/base/static/components/templates/map.tsx
This PR fixes an issue where initial slippy map routes were not correctly setting the map's initial viewport.
> fix(Map): set map viewport based on initial slippy route

- src/base/templates/base.hbs
Fixes this warning:
```
This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css
```
> fix(base.hbs): add missing mapbox css link
