mapseed/platform

src/sa_web/static/css/default.css
src/sa_web/static/js/views/map-view.js

This is a simple CSS fix for issue #9
I am unclear on where to put CSS in this project, so I chose a file that seems to be loading.  Please correct me if this is an inappropriate file for this code.
Also, I am a bit concerned about injecting HTML into the DOM from javascript using naked string literals.  Does this project have a JS templating system in place?

fix float property to address issue #9

---

src/flavors/duwamish_flavor/config.yml

- Increases the bounding box in config.yml
Fixes #5

Increase map boundary

---

src/flavors/duwamish_flavor/jstemplates/pages/background.html

fixed an error in the text and added a button to make closing the 'About' page more user friendly

added button at bottom of 'About' and page and changed $345 => $342

---

src/sa_web/static/css/default.css

css modified

---

src/flavors/duwamish_flavor/config.yml

fixed icon sizing / positioning (anchor)

---

src/sa_web/static/css/default.css
src/sa_web/templates/base.html

View the changes here: dev.lukeswart:8000 
and here 130.211.190.150:8000

Front-end redesigned

---

.travis.yml
README.md
ci/install.sh
ci/script.sh
src/project/local_settings.py.template
src/sa_web/jasmine/Gemfile.lock

Update gemfile
Remove 'sudo'
updates
Add path for pip requirements install
Change 'defaultflavor' to 'duwamish_flavor'; add .travis.yml comments
Remove database config settings
Add javascript tests
Enable disabled js tests (https://github.com/openplans/shareabouts/commit/012c571fe925fd81a086ab6150984b8703faee20)
Fix yaml syntax error
Add 2.6, update comments, add irc notifications

Re-enable python and javascript tests for travis CI

---

src/flavors/duwamish_flavor/config.yml

Also cleaned up some clutter in commented out lines that didn't seem necessary anymore and disabled geolocation on load until we figure out how to do it for mobile only and have a better user experience with it

changed layer names

---

src/flavors/happytrail/config.yml
src/flavors/raingardens/config.yml

for better Google/Facebook/etc scraping

added meta description for happy trail and raingardens

---

doc/WINDOWS_SETUP.md

Darryl changes

---

requirements.txt

This reverts commit 57e2d3558bb401e4c6ff8501993a627e0eefe80e.

Revert "remove postgres db requirements"

---

Dockerfile
createStaticDirs.sh
docker-data-container/Dockerfile

- This would be nice to implement at some point. But for now, it is getting in the way.

Remove permissions and user hierarchy

---

src/sa_web/static/js/views/app-view.js

- Fixes #140
- Ideally, we would find the css that is causing this issue, but this fix works for now.

Reset map when rendering point from url

---

src/flavors/duwamish_flavor/config.yml
src/sa_web/jstemplates/legend.html
src/sa_web/static/css/default.css

Hot fixes on Green Wall

---

src/flavors/duwamish_flavor/config.yml
src/sa_web/static/js/views/pages-nav-view.js

- Just add the flag 'hide_from_top_bar: true' to the top-level 'pages' array in config.yml, and the page will not appear in the nav-bar
- Fixes #212

Implement ability to remove nav pages from top bar

---

src/sa_web/static/js/views/app-view.js

- Fixes #239
- We can now use the attribute "{{layer.focused}} === true" in the config

Implement landmark layer focus

---

src/sa_web/static/css/default.css

Issue #258 needed someway to control size of video embeds in content. This fix controls the width of the object.
A better fix would just target video objects, but I'm not really sure where the content is coming from...

Added CSS to constrain size of iframe, object, and embed objects.

---

app-requirements-django19.txt
src/sa_web/templates/base.html

Should be all ready for Django 1.9, just try it out and see what happens.

Dvalp django19 upgrade

---

src/flavors/duwamish_flavor/config.yml
src/sa_web/static/js/views/map-view.js
src/sa_web/templates/base.html

We can now toggle the basemap between satellite and street view
We can now toggle the community-generated reports (shareabouts reports) on and off

add satellite and shareabouts map filters

---

src/flavors/duwamish-watershed/config.yml

fix error where community reports don't show up

---

src/sa_web/static/js/views/app-view.js

fix bug where landmark detail views do not load from a direct URL

---

src/sa_web/static/js/routes.js
src/sa_web/static/js/views/activity-view.js
src/sa_web/static/js/views/app-view.js
src/sa_web/views.py

**Don't merge yet!**
PR for issue #375

missing dataset_id parameter in views.api

---

src/sa_web/static/js/views/place-form-view.js

multiple map drag messages

---

doc/CONFIG.md

Documentation updates

---

src/sa_web/static/js/views/app-view.js

Fix disabled story bar controls bug

---

src/sa_web/static/js/views/place-list-view.js

Place list filtering fix

---

src/sa_web/jstemplates/place-detail-story-bar.html

Story bar title support

---

src/flavors/defaultflavor/config.yml

Update default flavor

---

src/sa_web/jstemplates/place-form.html

Remove form social auth

---

src/sa_web/jstemplates/place-detail.html
src/sa_web/static/js/handlebars-helpers.js
src/sa_web/static/scss/_content.scss

Place view updates

---

src/flavors/duwamish_flavor/config.yml
src/sa_web/jstemplates/gis-legend-content.html
src/sa_web/static/js/views/gis-legend-view.js
src/sa_web/static/js/views/map-view.js

feat(map): multiple exclusive basemaps

---

README.md

Add README instructions for configuring .env to load multiple datasets

---

src/flavors/duwamish_flavor/config.yml
src/flavors/lakewashington/jstemplates/pages/overview.html
src/sa_web/templates/base.html

- caching updates
- merge with master updates

updates for 0.7.0 release

---

src/sa_web/static/css/default.css
src/sa_web/static/scss/_header.scss

Greenways logo fix 447

---

src/sa_web/static/js/views/place-form-view.js

Fix unconfigured location types

---

src/sa_web/static/js/routes.js
src/sa_web/static/js/views/activity-view.js
src/sa_web/static/js/views/app-view.js
src/sa_web/static/js/views/place-form-view.js
src/sa_web/static/js/views/place-list-view.js

~~**UPDATE:** We still have a small bug wherein newly-created places with image attachments will not show their images immediately in the list view (although they will appear on a page load). I'll try to get this fixed tomorrow...~~
Fixes #458.
Note that for search and sorting to work properly on the list view, all place types on the list need to be configured in the dynamic form section of the config. This is because the search feature uses the dynamic form config to determine which fields it needs to search over. If no config for a given place type is found, places of that type will be excluded from *any* search or sort operation.
This was the issue behind disappearing places from the `trees` dataset.

Fix place list bugs

---

src/sa_web/static/js/views/place-form-view.js

Dynamic form model generation refactor

---

src/flavors/bogtobay/jstemplates/pages/contribute.html
src/flavors/bogtobay/jstemplates/pages/overview.html
src/flavors/bogtobay/locale/es/LC_MESSAGES/django.po

For bogtobay demo.
Spanish translations still in progress!

update spanish translations for bogtobay

---

src/sa_web/static/js/views/app-view.js
src/sa_web/static/js/views/map-view.js

Show all layers when legend disabled

---

src/flavors/bogtobay/config.yml
src/flavors/duwamish_flavor/config.yml
src/flavors/lakewashington/config.yml
src/flavors/pugetsound/config.yml
src/flavors/rail/config.yml
src/sa_web/static/js/routes.js
src/sa_web/static/js/views/app-view.js
src/sa_web/static/js/views/map-view.js

Just some minor changes like comments/whitespaces/refactorings/etc

Minor updates

---

src/flavors/bogtobay/config.yml
src/flavors/defaultflavor/config.yml
src/flavors/duwamish-watershed/config.yml
src/flavors/greenways/config.yml
src/flavors/gtopenspace/config.yml
src/flavors/lakewashington/config.yml
src/flavors/pugetsound/config.yml
src/flavors/rail/config.yml
src/flavors/raingardens/config.yml
src/flavors/snoqualmie/config.yml
src/flavors/trees/config.yml
src/flavors/waterfront/config.yml
src/flavors/willamette/config.yml
src/sa_web/static/js/models.js

Update flavor configs

---

src/sa_web/jstemplates/place-form.html
src/sa_web/static/js/views/place-form-view.js

Fix form geolocation bug

---

src/sa_web/jstemplates/place-detail.html

List view page reload fix

---

src/flavors/duwamish_flavor/config.yml

Minor updates for CSO marker colors

Update duwamish config with new CSO marker colors

---

src/sa_web/static/js/views/activity-view.js

Remove unnecessary looping over place collections in ActivityView

---

src/sa_web/jstemplates/place-form.html
src/sa_web/static/js/utils.js
src/sa_web/static/js/views/app-view.js
src/sa_web/static/js/views/place-form-view.js

* Attempt to use localStorage to store autocomplete values; fall back to cookies
* Fix bug where comment forms don't work correctly with autocomplete feature

Form autocompletion updates

---

src/sa_web/static/js/views/app-view.js

Doing so overrides the animated transition effect.

Don't reset setView() on story transitions

---

src/sa_web/static/css/default.css
src/sa_web/static/css/leaflet-sidebar.css
src/sa_web/static/scss/_content.scss
src/sa_web/static/scss/_map.scss
src/sa_web/static/scss/_media.scss

Reverts smartercleanup/platform#567

Revert "working on #content"

---

src/flavors/pboakland/config.yml
src/flavors/pboakland/static/css/custom.css
src/flavors/pboakland/static/js/views/legend-view.js
src/flavors/pboakland/static/js/views/sidebar-view.js

- activate right sidebar
- put legend in right sidebar and remove from leaflet panel

pboakland updates

---

src/base/static/js/views/activity-view.js

fix bug that causes wrong article (a/an) to be used with location type labels in the activity stream

fix ungrammatical activity list items

---

src/flavors/pboakland/static/css/custom.css
src/flavors/pboakland/static/js/views/app-view.js

When a page is visible, the list button will become the add place
button, and the list button will disappear. When other content is
visible or no content is visible, the add place and list buttons
will appear in their normal places.

Swap list and add place buttons on page view

---

src/base/static/js/models.js

Update regex used to pull out titles from landmark html

---

src/base/static/js/views/app-view.js

add back code that resets dynamic form state on panel close

---

src/flavors/bogtobay/static/css/custom.css
src/flavors/bogtobay/templates/index.html

* Adjust size of grouping form controls
* use block layout for overview page content at mobile size
* use img tag for bogtobay logo instead of inserting via CSS

bogtobay design updates

---

src/base/static/js/views/place-list-view.js

* Lazy render list test
* Sorting optimizations

Raingarden performance test

---

src/base/static/js/views/app-view.js

Addresses: #468.
* When creating a new place, ensure the place's map layer is visible on place creation
* Also ensure a place's map layer is visible when a place is visited directly on map load
* Minor refactoring of layer control code in the AppView

Ensure target layer is visible on place creation

---

src/base/static/js/utils.js

A bug in the landmark/place loading code could cause a landmark-as-place model to fire its `onNotFound()` callback, even when the model had been found in another collection.
When directly loading a place with landmark-style url (e.g. `/marra`), this bug would result in the page's url being reset to the base url, despite the place loading correctly.

Fix a bug where onNotFound() is called even when a model has been found

---

src/base/jstemplates/activity-list-item.html
src/base/static/js/views/activity-view.js
src/flavors/greensboropb/config.yml
src/flavors/greensboropb/static/js/views/layer-view.js

- add 2015 data layer
- remove onMarkerClick override, as it interferes with our fix to the off-center bug
- add admin-only description field to form categories to support 2015 data

Greensboropb updates

---

src/base/static/js/views/app-view.js
src/base/static/js/views/place-form-view.js

Addresses: #691 
Fix bug where geocode address view isn't rendered for dynamic form categories.

Fix geocode address view bug

---

src/flavors/central-puget-sound/config.yml
src/flavors/central-puget-sound/static/css/custom.css

- update logo color
- add hydrography and hydroregions WTMS layers

Puget sound flavor updates

---

src/base/jstemplates/place-form-category-buttons.html
src/base/jstemplates/place-form.html
src/base/static/js/utils.js
src/base/static/js/views/basic-layer-view.js
src/base/static/js/views/geometry-editor-view.js
src/base/static/js/views/layer-view.js
src/base/static/js/views/place-form-view.js
src/base/static/scss/_buttons.scss
src/base/static/scss/_forms.scss
src/flavors/duwamish_flavor/config.yml
src/flavors/lakewashington/config.yml

- fix published/not published bug on lake washington flavor
- remove form filler silhouettes
- tighten spacing around form category selection buttons
- remove name, image, and email fields on lake washington and duwamish featured places
- fix a typo in form field processing that caused some form fields not to render
- fix unintended changes to duwamish default layer visibility settings
- change default polygon fill and stroke colors in geometry drawing tool
- remove legacy editor code that made landmarks editable
- on form, update url-title field based on title field content
- on form, default to edit mode on geometry creation
- don't show submitter metadata on featured place detail views

Numerous tweaks and fixes for the editor

---

src/base/static/js/views/geometry-editor-view.js

- fix a bug where geometry isn't immediately editable in edit mode

editor update

---

src/base/jstemplates/right-sidebar.html
src/base/static/js/views/app-view.js
src/base/static/js/views/right-sidebar-view.js
src/base/templates/base.html

- create a container view for the right-clinging sidebar

sidebar updates

---

src/base/static/js/views/right-sidebar-view.js
src/flavors/duwamish_flavor/config.yml

- fix an issue with CSO layer style rules

Duwamish style rule updates

---

package.json
webpack.config.js

Still need to test this, but it seems to be working
Resolves #690

Add babel-loader transpiler to build

---

.eslintrc

We can reconfigure this more as needed.

Add .eslintrc

---

src/flavors/lakewashington/config.yml

**WAIT TO MERGE UNTIL DATA HAS BEEN INGESTED ON PROD SERVER**

update lake wa config to use ingested landmark data

---

src/base/static/js/models/model-utils.js
src/base/static/js/views/app-view.js
src/flavors/lakewashington/config.yml

- allow story mode to control zoom for polygon layers
- add a `default_basemap` option to stories

Story control updates

---

src/base/static/js/models/model-utils.js
src/base/static/js/views/app-view.js
src/base/static/js/views/right-sidebar-view.js
src/flavors/lakewashington/config.yml

Use the flag sidebar_icon_url to configure custom icons, e.g.:
```
sidebar_icon_url: /static/css/images/markers/map-pin-marker.png
```

Make sidebar icons customizable in the story config

---

src/base/jstemplates/place-detail.html
src/base/static/scss/_listview.scss

Addresses: #677.
Improvements to the list view:
* Fix bug where show on map button doesn't respect landmarks-as-places urls
* Improve formatting for landmarks-as-places in the list view
* Restrict list item height
* Restrict img and iframe sizes

List view improvements

---

src/base/static/js/views/layer-view.js

The culprit was the layer view optimization code...

Fix a bug that caused newly-created places to not be visible

---

src/base/static/js/views/layer-view.js

TL;DR -- this PR fixes an issue that caused landmark polygons and linestrings to be styled incorrectly.
Recent modifications made to the way we evaluate style rules introduced changes that interfere with old landmark data that still uses the `mapbox` set of style rules. This went unnoticed for awhile since we also recently switched over to loading the `restoration` and `vision` data from their ingested place model equivalents, where style rules are read directly from the place model.
This PR restores full config-based GeoJSON styling capabilities for layers with polygon and linestring geometry that are styled with the `mapbox` set of style rules. It does so by making an assumption: namely that any custom style rules are found in a dedicated `style` object intended to override styling …

Fix landmark style rule evaluation

---

src/flavors/central-puget-sound/config.yml
src/flavors/central-puget-sound/jstemplates/pages-nav.html
src/flavors/central-puget-sound/static/css/custom.css
src/flavors/central-puget-sound/static/js/views/pages-nav-view.js

- position add a report button in header on large screens
- enable right-clinging page nav buttons
- remove language menu
- set map background to dark gray

CPS flavor updates

---

src/base/jstemplates/gis-legend-content.html
src/base/static/js/views/app-view.js
src/base/static/js/views/gis-legend-view.js
src/base/static/js/views/map-view.js
src/base/static/libs/leaflet.argo.js
src/base/static/scss/_legend.scss
src/base/static/scss/_variables.scss

- add iconography for layer loading, loaded, and error conditions
- the layer panel will display a spinner next to layers that are loading, a green check next to layers that have loaded and are visible, and a red exclamation point next to layers that encountered a problem

Layer panel improvements

---

src/base/static/js/views/gis-legend-view.js
src/base/static/js/views/layer-info-window-view.js
src/base/static/js/views/sidebar-view.js
src/base/static/scss/_map.scss
src/base/templates/base.html

- toggle info window visibility on info icon click
- hide info windows with quick fade when the user scrolls the layer panel container beyond a set threshold value

Layer info window improvements

---

src/base/jstemplates/place-detail-edit-bar.html
src/base/jstemplates/place-detail-promotion-bar.html
src/base/jstemplates/place-detail-story-bar-tagline.html
src/base/jstemplates/place-detail-story-bar.html
src/base/jstemplates/place-detail.html
src/base/static/js/views/app-view.js
src/base/static/js/views/landmark-detail-view.js
src/base/static/js/views/place-detail-view.js
src/base/static/scss/_buttons.scss
src/base/static/scss/_content.scss
src/base/static/scss/_media.scss
src/base/templates/base.html

- remove minimize/maximize tabs and associated functionality
- adjust edit bar spacing and content
- remove story nav bar arrows on desktop size
- improve story bar design and markup
- remove bottom story nav bar entirely

Detail view improvements

---

src/flavors/central-puget-sound/config.yml
src/flavors/central-puget-sound/static/js/views/place-form-view.js
src/flavors/lakewashington/config.yml

- impervious surfaces layer
- full school and corresponding districts list
- KC cities layer
- info window content
- Puyallup story point
- parcels layer

MW/CPS content/layer updates

---

package.json
src/base/jstemplates/place-form-field-types.html
src/base/static/js/utils.js
src/base/static/js/views/place-form-view.js
src/base/static/scss/_forms.scss
src/flavors/central-puget-sound/config.yml

Revert "Add combobox autocomplete feature"

---

src/flavors/central-puget-sound/config.yml

- move address field to top of form
- remove title placeholder text
- update sidebar icons

Update MW/CPS flavor

---

package.json
src/base/jstemplates/place-form-field-types.html
src/base/static/js/utils.js
src/base/static/js/views/place-form-view.js
src/base/static/scss/_forms.scss
src/flavors/central-puget-sound/config.yml
yarn.lock

**WAIT TO MERGE TO CONFIRM THIS WORKS IN THE DEPLOYMENT ENVIRONMENT**
This PR adds the ability to create autocomplete combobox dropdown fields on the dynamic form. Use the `type: dropdown-autocomplete` flag to create an autocomplete field.
Following suggestions in [this issue](https://github.com/mapseed/platform/issues/781), we have a fork of the [alphagov/accessible-autocomplete module](https://github.com/alphagov/accessible-autocomplete) with [minor modifications](https://github.com/mapseed/accessible-autocomplete/pull/1) for our own purposes.

Add combobox autocomplete feature

---

src/flavors/duwamish_flavor/config.yml

- add Port of Seattle-controlled featured place to duwamish_flavor
- remove extraneous `iconUrl`s in featured place style rules

Port of Seattle featured place category for Hey Duwamish

---

src/flavors/central-puget-sound/config.yml

- new story points
- fix schools layer

update mywater schools layer and stories

---

README.md
src/base/jstemplates/auth-nav.html
src/base/static/scss/_header.scss

Add a google login button, in google red.
Wait to merge until https://github.com/mapseed/api/pull/88 is merged and deployed.

add google login button

---

package-lock.json
package.json
scripts/deploy.js

`take-2` is in the branch name because I had some conflicts at first and had to cherry-pick... maybe a rebase issue?
Some stuff to think about:
- Besides in the code, is there a place to document the necessary environment variables?
- There's no TLS/SSL stuff in here but it doesn't look too hard to add.
- What's the DNS look like? I'm no expert, maybe someone with dev deploy access can put it through its paces in a production-like environment.

Deploy script for the static site

---

scripts/deploy.js
static-build.js

* gzip css and js bundles
* add explicit `Content-Encoding` support for gzipped files during S3 deploy

gzip bundles

---

src/base/jstemplates/place-form-field-types.html
src/base/static/js/utils.js
src/base/static/js/views/place-form-view.js
src/base/static/scss/_forms.scss

Sample config for range inputs:
```
- name: private-age
prompt: _(How old are you?)
type: range
max: 100
min: 1
defaultValue: 50
autocomplete: true
```

Add range input type option to form

---

src/flavors/nyrp/config.yml
src/flavors/nyrp/jstemplates/place-form-field-types.html
src/flavors/nyrp/jstemplates/place-form-fields.html
src/flavors/nyrp/jstemplates/place-form-multi-stage.html
src/flavors/nyrp/static/css/custom.css
src/flavors/nyrp/static/js/views/app-view.js
src/flavors/nyrp/static/js/views/place-form-view.js

NYRP flavor updates

---

src/flavors/williams/static/components/input-explorer-category-menu.js
src/flavors/williams/static/components/input-explorer-input-list-header.js
src/flavors/williams/static/components/input-explorer.js

* fix summary categories and subcategories appearing in form
* add all subcategory selector

Williams flavor updates

---

src/flavors/williams/static/components/input-explorer-input-item.js
src/flavors/williams/static/components/input-explorer-input-item.scss
src/flavors/williams/static/components/input-explorer-input-list-header.js
src/flavors/williams/static/components/input-explorer.js
src/flavors/williams/static/js/views/place-form-view.js

* logged-in admins can set/unset sticky status
* sticky fields sort to top
* comments sort by `created_datetime` otherwise
* make subcategory fields radio buttons

add sticky functionality to comment explorer

---

src/flavors/williams/jstemplates/legend.html
src/flavors/williams/static/css/custom.css

* change legend panel icon
* change legend panel styling

Williams flavor legend panel updates

---

src/flavors/williams/static/css/custom.css
yarn.lock

Made some CSS tweeks but could not do a few of the  changes i.e. making comments visible in mobile or hidding the "Add comment" button while on the Add Comment Form.

Alex css tweeks

---

src/base/static/components/input-form/__tests__/__snapshots__/input-form.test.js.snap
src/base/static/components/input-form/__tests__/input-form.test.js

Update tests to accommodate changes introduced in #907.

chore(input form test): update test and snapshot

---

src/base/static/components/form-fields/types/add-attachment-button.js
src/base/static/components/form-fields/types/add-attachment-button.scss
src/base/static/components/form-fields/types/file-field.js
src/base/static/components/form-fields/types/file-field.scss
src/base/static/stylesheets/themes/default-theme/variables.scss

Refactor the `AddAttachmentButton` to fix issues with it in Firefox.

fix(attachment button) fix issues in firefox

---

src/base/static/js/views/layer-view.js
src/flavors/central-puget-sound/config.yml

* A previous pull broke the filters; this PR fixes them
* Fix cover image button on featured place form

Fix a couple of mywater issues

---

src/flavors/snohomish/config.yml
src/flavors/snohomish/static/css/custom.css

Update snohomish flavor's config to support triggered datetime fields.

refactor(snohomish): update form for trigger fields

---

src/base/static/components/atoms/feedback.js
src/base/static/components/atoms/feedback.scss
src/base/static/components/form-fields/field-definitions.js
src/base/static/components/form-fields/types/datetime-field.js
src/base/static/components/molecules/form-stage-header-bar.js
src/base/static/components/molecules/form-stage-header-bar.scss
src/flavors/snohomish/config.yml
src/flavors/snohomish/jstemplates/add-places.html
src/flavors/snohomish/jstemplates/pages/sign-in.html
src/flavors/snohomish/static/css/custom.css
src/flavors/snohomish/static/js/views/app-view.js

* route to `/new` after custom page sign in workflow
* add "continue as guest" button to sign in page
* route to sign in page from add a report button\
* improved form styling
* form stage header info modal trigger button
* remove time select from datetime fields

Snohomish flavor updates

---

src/base/static/components/form-fields/form-field.js
src/base/static/components/form-fields/form-field.scss
src/base/static/components/input-form/index.scss
src/flavors/defaultflavor/config.yml
src/flavors/snohomish/config.yml

Add the ability to insert an info modal content trigger inline with a form field's prompt.

feat: add inline field prompt modal trigger functionality

---

src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/snohomish-field-summary.js
src/base/static/js/views/layer-view.js
src/flavors/bathgate/config.yml
src/flavors/snohomish/config.yml
src/flavors/snohomish/static/css/custom.css

* remove metadata bar on detail views
* "1 Actions" -> "1 Action"
* selected marker on top
* remove cartodb

Flavor tweaks

---

src/flavors/pboakland/config.yml
src/flavors/pboakland/static/css/custom.css
src/flavors/pboakland/static/js/views/layer-view.js

Design and feature tweaks to the `pboakland` flavor.

PBOakland flavor tweaks

---

src/base/static/js/views/app-view.js

This PR adds support for Redux Dev Tools: http://extension.remotedev.io/
I find it very useful - worth giving it a shot.

chore(app-view) enable redux dev tools

---

src/base/static/components/molecules/cover-image.js
src/base/static/components/place-detail/field-summary.js
src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/place-detail-editor.js
src/base/static/components/place-detail/snohomish-field-summary.js
src/base/static/components/place-detail/vv-field-summary.js
src/flavors/snohomish/config.yml
src/flavors/snohomish/static/css/custom.css

**IN PROGRESS**
* Decrease mobile header font size
* Decrease mobile logo size
* Move action summary above attachments on detail views
* Add progress indicator to "skip section" checkboxes on form

Snohmish flavor updates

---

src/base/static/js/views/sidebar-view.js
src/flavors/greensboropb/static/js/views/sidebar-view.js

refactor(SidebarViews): remove unused imports

---

src/flavors/central-puget-sound/config.yml
src/flavors/central-puget-sound/jstemplates/pages-nav.html
src/flavors/central-puget-sound/jstemplates/pages/classroom.html
src/flavors/central-puget-sound/static/css/custom.css
src/flavors/central-puget-sound/static/js/views/app-view.js
src/flavors/central-puget-sound/static/js/views/sidebar-view.js
src/flavors/central-puget-sound/templates/index.html

* New `classroom` holding page
* Header bar tweaks
* Add layer menu flyout link in header

Mywater design tweaks

---

src/base/jstemplates/add-places.html
src/base/static/client/mapseed-api-client.js
src/base/static/components/atoms/buttons.js
src/base/static/components/atoms/feedback.js
src/base/static/components/input-form/input-form-category-button.js
src/base/static/components/input-form/input-form-category-button.scss
src/base/static/components/input-form/input-form-category-selector.js
src/base/static/components/molecules/activity-item.js
src/base/static/components/molecules/map-layer-selector.js
src/base/static/components/organisms/left-sidebar.scss
src/base/static/components/place-detail/index.scss
src/base/static/components/place-detail/survey-response.scss
src/base/static/components/place-detail/survey.js
src/base/static/components/place-detail/survey.scss
src/base/static/js/views/app-view.js
src/base/static/scss/_map.scss
src/base/static/scss/_media.scss
src/flavors/pbdurham/config.yml
src/flavors/pbdurham/static/css/custom.css

Closes: https://github.com/jalMogo/mgmt/issues/97
Closes: https://github.com/jalMogo/mgmt/issues/98
Closes: https://github.com/jalMogo/mgmt/issues/99
Closes: https://github.com/jalMogo/mgmt/issues/92
Closes: https://github.com/jalMogo/mgmt/issues/86
Also addresses styling on the `pbdurham` flavor.

Cosmetic bug fixes

---

src/base/static/js/models/paginated-collection.js

Closes: https://github.com/jalMogo/mgmt/issues/120

fix(PaginatedCollection): avoid division by 0 on empty Place collections

---

src/base/static/components/organisms/main-map.js
src/base/static/components/place-detail/place-detail-editor.js
src/base/static/constants.js

Closes: https://github.com/jalMogo/mgmt/issues/118

fix(MainMap): remove deleted geometry correctly

---

src/base/static/js/models/place-model.js
src/base/static/js/models/submission-model.js

Depends on merging: https://github.com/mapseed/api/pull/148 first
Fixes: https://github.com/jalMogo/mgmt/issues/107

fix(placeModel): make actions silent when updating a place or submission

---

scripts/static-build.js

Closes: https://github.com/jalMogo/mgmt/issues/127

fix(static-build.js): use synchronous gzip method

---

package-lock.json
package.json

Regenerate `package-lock.json` using `node 8.11.3` and `npm 5.6.0`.
Also remove the unused `togeojson` dependency.

chore(package.json): remove unused dep and update lockfile

---

package-lock.json
package.json
webpack.config.js

Closes: https://github.com/jalMogo/mgmt/issues/128

chore(package.json): add whatwg-fetch polyfill

---

src/base/static/components/atoms/buttons.js
src/base/static/components/atoms/buttons.scss
src/base/static/components/molecules/form-stage-control-bar.js
src/base/static/components/templates/right-sidebar.js
src/base/static/js/views/app-view.js
src/flavors/augusta/static/js/views/app-view.js
src/flavors/bathgate/static/js/views/app-view.js
src/flavors/central-puget-sound/static/js/views/app-view.js
src/flavors/greensboropb/static/css/custom.css
src/flavors/hull/static/js/views/app-view.js
src/flavors/manzanares/static/js/views/app-view.js
src/flavors/pugetsound/static/js/views/app-view.js
src/flavors/snohomish/static/js/views/app-view.js
src/flavors/williams/static/js/views/app-view.js

Refactors our Button component so that it is no longer dependent on LegacyButton, and it is using CSS-in-JS.
This PR also includes a minor refactor to AppView and RightSidebar, so that we are not relying on Backbone events.

updates to CSS-in-JS Button component, and right sidebar

---

src/base/static/components/organisms/main-map.js
src/base/static/js/views/app-view.js

**WIP**
Closes: https://github.com/jalMogo/mgmt/issues/147
Closes: https://github.com/jalMogo/mgmt/issues/138
Closes: https://github.com/jalMogo/mgmt/issues/142

Fix a few bugs related to deeplinking

---

src/base/static/js/views/app-view.js

Closes: https://github.com/jalMogo/mgmt/issues/154

fix(AppView): make sure we're using localized config values in React

---

src/base/static/scss/_media.scss
src/base/static/scss/_sidebar.scss

Closes: https://github.com/jalMogo/mgmt/issues/161

fix(LeftSidebar): correct height when geocode address bar is visible

---

src/base/static/components/molecules/form-field-types/map-drawing-toolbar.js
src/base/static/components/organisms/main-map.js
src/base/static/libs/maps/mapboxgl-provider.js

Closes: https://github.com/jalMogo/mgmt/issues/166
Closes: https://github.com/jalMogo/mgmt/issues/167

MapDrawingToolbar bug fixes

---

src/base/static/components/organisms/story-navigator.js
src/base/static/components/templates/right-sidebar.js
src/base/static/js/views/app-view.js
src/base/static/utils/collection-utils.js
src/base/static/utils/story-utils.js
src/flavors/snohomish/static/js/views/app-view.js

This fix has already been deployed

fix(StoryNavigator): render places from redux store

---

src/base/static/components/atoms/feedback.js
src/base/static/components/molecules/map-filter-selector.js
src/base/static/components/molecules/map-layer-selector.js
src/base/static/components/molecules/map-legend-item.js
src/base/static/components/molecules/map-legend-item.scss

Closes: https://github.com/jalMogo/mgmt/issues/184

fix(MapLegendItem): IE11 layout

---

src/base/static/components/place-detail/index.js
src/base/static/utils/scroll-helpers.js

Closes: https://github.com/jalMogo/mgmt/issues/192

refactor(PlaceDetail): don't use scrollTo helper when routing to comments

---

src/base/static/components/atoms/imagery.js
src/base/static/components/form-fields/field-definitions.js
src/base/static/components/form-fields/types/index.js
src/base/static/components/molecules/form-field-types/geolocate-field.js
src/base/static/components/organisms/main-map.js
src/base/static/constants.js
src/base/static/libs/maps/mapboxgl-provider.js
src/flavors/defaultflavor/config.json

Closes: https://github.com/jalMogo/mgmt/issues/189

feat(GeolocateField): add input form geolocate field

---

src/base/static/components/input-form/index.js
src/base/static/state/ducks/map.js
src/flavors/defaultflavor/config.json

Closes: https://github.com/jalMogo/mgmt/issues/165

feat(InputForm): add form stage layer switching feature

---

src/base/static/js/routes.js

Closes: https://github.com/jalMogo/mgmt/issues/139

feat(routes.js): disable /new route when place adding is disabled

---

src/flavors/argentina/config.json

Replicates changes in https://github.com/mapseed/platform/pull/1143.

refactor(argentina): add rich text fields, new content

---

package-lock.json
package.json

- Fixes a security warning with webpack-dev-server
- Bumps react to 16.8 - we now have "hooks" :tada:

chore(package.json): update webpack-dev-server and react

---

src/flavors/palouse/config.json

refactor(palouse): content

---

src/base/static/client/mapseed-api-client/place.js
src/base/static/components/input-form/index.js
src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/place-detail-editor.js

Addresses: https://github.com/jalMogo/mgmt/issues/241
Also fix a bug that would cause the editor to hang when submitting an invalid form.

fix(apiClient): include private query params for admins when creating a Place

---

src/flavors/pbdurham/config.json

Updating group permissions to be more consistent with durham's needs.

feat(durhamConfig): update groups

---

src/flavors/pbdurham/config.json

This reverts commit f22a8a8b4a62af902f84316e70481b6ecd09e908.

Revert "feat(durhamConfig): update groups"

---

src/base/static/components/organisms/place-list.js
src/base/static/components/organisms/site-header.js
src/base/static/components/theme-provider.js
src/base/static/js/views/app-view.js
src/base/static/state/ducks/app-config.js

This PR cleans up our theming to define a new ThemeProvider HOC to manage our Emotion and MUI theme providers.

MUI and Emotion theming

---

src/base/static/components/templates/right-sidebar.js
src/base/static/js/views/app-view.js
src/flavors/argentina/config.json
src/flavors/bellevue-bike-share/config.json
src/flavors/palouse/config.json
src/flavors/pbdurham/config.json

Hacks ahoy! This PR has some very temporary layout fixes/hacks to hold us over until when the AppView port is finished.

refactor(AppView): layout hacks/fixes

---

src/base/static/client/mapseed-api-client/place.js
src/base/static/components/place-detail/place-detail-editor.js
src/base/static/state/ducks/places.js

Closes: https://github.com/jalMogo/mgmt/issues/241

refactor(apiClient): send credentials with PUT requests

---

.eslintrc
package-lock.json
package.json
src/base/static/components/atoms/layout.js
src/base/static/components/organisms/invite-modal.js
src/base/static/components/organisms/offline-download-menu.js
src/base/static/components/templates/main-map.js
src/base/static/js/routes.js
src/base/static/js/views/app-view.js
src/base/static/state/ducks/user.js
webpack.config.js

Adding invite links.
This is up on durham staging.

feat(routes): add mixpanel and /invite link

---

src/base/static/components/atoms/typography.js
src/base/static/components/input-form/index.js
src/base/static/components/organisms/site-header.js
src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/place-detail-editor.js
src/base/static/components/templates/map.js
src/base/static/utils/layout-utils.js
src/base/static/utils/scroll-helpers.js

* correct map container sizing on mobile
* close site header on mobile when menu item is selected
* correct scroll to top behavior on mobile

Fix a few issues after AppView port

---

src/base/static/components/molecules/add-place-button.js
src/base/static/components/molecules/place-detail-fields/textarea.js
src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/pbdurham-project-proposal-field-summary.js

A few tweaks to the custom detail view post-`AppView` port.

pbdurham flavor tweaks

---

src/base/static/components/organisms/filter-menu.js
src/base/static/components/organisms/main-map.js
src/base/static/state/ducks/datasets.js
src/base/static/state/ducks/places.js
src/flavors/pbdurham/config.json

This PR allows us to filter Proposals.
this branch is up on durham staging.

feat(filters): multi-dataset filters

---

src/base/static/components/organisms/activity-stream.js

Addresses: https://github.com/jalMogo/mgmt/issues/253

fix(ActivityStream): don't render activity for non-authed private Places

---

src/flavors/kittitas-vsp/config.json

refactor(kittitas-vsp): content

---

src/base/static/js/routes.js

Closes: https://github.com/jalMogo/mgmt/issues/256

fix(routes): ensure edit mode is untoggled when routing to a place

---

src/base/static/js/utils.js

`this.analytics` is undefined, preventing clients from editing their places.
@goldpbear can you look into this?

hotfix(analytics)

---

src/base/static/components/atoms/buttons.js
src/base/static/components/molecules/user-menu.js
src/base/static/components/organisms/offline-download-menu.js
src/base/static/state/ducks/map-config.js

Now using react hooks with react redux!
Also fixes some layout and config bugs...

fix(offlineDownloadMenu): use hooks, some styling tweaks

---

src/base/static/components/organisms/main-map.js
src/base/static/state/ducks/map-drawing-toolbar.js
src/flavors/pbdemo/config.json

Closes: https://github.com/jalMogo/mgmt/issues/267

fix(MainMap): fix a bug where re-routing to the map with draw mode enabled causes a crash

---

src/theme.js

Fixes a styling issue on some custom pages.

fix(theme.js): make sure page styling doesn't override inline styles

---

scripts/deploy.js

Closes: https://github.com/jalMogo/mgmt/issues/277

fix(deploy): fix broken lazy loading modules on IE11

---

src/base/static/client/mapseed-api-client.js
src/base/static/client/mapseed-api-client/activity.js
src/base/static/client/mapseed-api-client/session.js
src/base/static/components/app.tsx
src/base/static/components/molecules/place-list-item.js
src/base/static/components/organisms/activity-stream.js
src/base/static/components/organisms/main-map.js
src/base/static/components/organisms/story-navigator.js
src/base/static/components/place-detail/index.js
src/base/static/components/place-detail/pbdurham-project-proposal-field-summary.js
src/base/static/components/place-detail/place-detail-editor.js
src/base/static/components/templates/dashboard.js
src/base/static/components/templates/map.tsx
src/base/static/js/utils.js
src/base/static/state/ducks/places.js
src/base/static/utils/place-utils.js

Closes: https://github.com/jalMogo/mgmt/issues/278
* Fix unclickable Places bug on direct route
* `await` session token fetch to avoid race condition and `null` session token value
* `_datasetSlug` -> `datasetSlug` and `_clientSlug` -> `clientSlug`

A few minor fixes

---

src/base/static/client/analysis-client.js
src/base/static/components/app.tsx
src/base/static/components/input-form/form-category-menu-wrapper.js
src/base/static/components/input-form/index.js
src/base/static/components/organisms/content-panel.js
src/base/static/components/organisms/main-map.js
src/base/static/components/templates/map.tsx
src/base/static/state/ducks/analysis.js
src/base/static/state/ducks/map.js
src/base/static/state/ducks/place-config.js
src/base/static/state/reducers.js
src/base/static/utils/geo.js
src/flavors/defaultflavor/config.json

Closes: https://github.com/jalMogo/mgmt/issues/281

Fetch geospatial analysis target data separately from Mapbox

---

package-lock.json
package.json
src/base/static/client/pdf-service-client.js
src/base/static/components/input-form/index.js
src/base/static/components/templates/report.tsx
src/base/static/state/ducks/datasets-config.js
src/flavors/kittitas-firewise/config.json

This PR triggers a PDF download on Place submission provided a flavor is configured for PDF reports.

feat: PDF download on Place submission

---

src/base/static/components/organisms/invite-modal.js
src/base/static/state/ducks/user.js

Depends on merging the corresponding PR for our API.
TODO: perform login test, place creation, deletion, workflow.

fix(UserDuck): remove provider_id

---

scripts/deploy.js

Closes: https://github.com/jalMogo/mgmt/issues/266
Depends on: https://github.com/mapseed/s3-website/pull/2

fix(deploy): set ContentEncoding metadata on S3 object copy

---

src/base/static/utils/place-utils.js

Closes: https://github.com/jalMogo/mgmt/issues/292

fix(placeUtils): incorrect datasetSlugs

---

src/base/static/components/app.tsx
src/base/static/components/templates/dashboard.js

Closes: https://github.com/jalMogo/mgmt/issues/293

fix(App): layout tweaks

---

src/base/static/components/molecules/add-place-button.js
src/base/static/components/organisms/content-panel.js
src/base/static/components/templates/map.tsx
src/base/static/utils/layout-utils.js

Closes: https://github.com/jalMogo/mgmt/issues/294
This PR also adds Mixpanel tracking for invalid layout configurations.

fix(App): mobile layout with AddPlaceButton visible

---

src/base/static/state/ducks/featured-places-config.js

TS will catch this kind of stuff in the near future...

fix(featuredPlacesDuck): iconUrl

---

src/base/static/components/atoms/buttons.js
src/flavors/mississippi/config.json

feat(mississippiConfig)

---

src/base/static/components/app.tsx

Closes: https://github.com/jalMogo/mgmt/issues/325

fix(App): restore iOS inertia-based scrolling

---

src/base/static/components/input-form/index.js

Closes: https://github.com/jalMogo/mgmt/issues/338

fix(InputForm): place submission crash

---

src/base/static/components/organisms/main-map.tsx

Closes: https://github.com/jalMogo/mgmt/issues/341

fix(MainMap): restore scroll zoom around center behavior

---

src/base/static/components/organisms/main-map.tsx

Closes: https://github.com/jalMogo/mgmt/issues/342

fix(MainMap): center correctly when scrollZoomAroundCenter is true

---

src/base/static/components/molecules/add-place-button.js
src/base/static/components/templates/map.tsx

Closes: https://github.com/jalMogo/mgmt/issues/345

fix(AddPlaceButton): forward ref

---

src/base/static/components/organisms/map-measurement-overlay.tsx

Closes: https://github.com/jalMogo/mgmt/issues/347

fix(MeasurementTool): click handler

---

src/base/static/components/form-fields/field-definitions.js
src/base/static/components/organisms/reports/kittitas-firewise/components.js
src/base/static/components/organisms/reports/kittitas-firewise/report.js
src/base/templates/base.hbs
src/flavors/kittitas-firewise/config.json
src/flavors/kittitas-firewise/static/css/custom.css
src/theme.js

Updates to `kittitas-firewise`.
This PR also reverts the way we load webfonts. For some reason that I couldn't figure out the previous approach created issues for Puppeteer and the pdf generator.

refactor(kittitas-firewise): content

---

src/base/static/components/templates/map.tsx

Closes: https://github.com/jalMogo/mgmt/issues/358

fix(Map): correct map container height when no default start page is visible

---

package-lock.json
package.json

Revert "chore(deps-dev): bump webpack from 4.39.0 to 4.39.1"

---

package-lock.json
package.json

Revert "chore(deps-dev): bump babel-plugin-emotion from 10.0.14 to 10.0.15"

---

package-lock.json
package.json

Revert "chore(deps-dev): bump enzyme-to-json from 3.3.5 to 3.4.0"

---

package-lock.json
package.json

Revert "chore(deps): bump i18next from 17.0.8 to 17.0.9"

---

src/base/static/components/molecules/login-modal.tsx
src/base/templates/base.hbs
src/theme.tsx

feat(LoginModal): add privacy policy, UX tweaks

---

.eslintrc.js
src/base/static/index.tsx
src/base/static/service-worker.ts
src/base/static/utils/mixpanel.js
src/base/templates/base.hbs
webpack.config.js

Fixes an issue with our service workers.
Should also help with perf by removing our SW registration from our index.html template.
This PR also prevents SW registration while in development mode.

fix(serviceWorker)

---

src/base/static/components/input-form/index.js
src/base/static/components/organisms/site-header.tsx
src/base/static/components/place-detail/place-detail-editor.js
src/flavors/spokane/config.json
src/flavors/spokane/static/css/custom.css

Also update `PlaceDetailEditor` for new visibility triggering.

refactor(spokane): content

---

package-lock.json
package.json

Revert "chore(deps): bump @material-ui/core from 4.4.0 to 4.4.1"

---

package-lock.json
package.json

Revert "chore(deps-dev): bump @typescript-eslint/parser from 1.13.0 to 2.2.0"

---

package-lock.json
package.json

Revert "chore(deps): bump @types/react-router from 5.0.3 to 5.0.4"

---

package-lock.json
package.json
src/base/static/components/atoms/imagery.js
src/base/static/components/input-form/index.js
src/base/static/components/molecules/form-field-types/geocoding-field.tsx
src/base/static/components/molecules/metadata-bar.tsx
src/base/static/components/organisms/dashboard/free-donut-chart.tsx
src/base/static/components/place-detail/editor-bar.tsx
src/base/static/components/place-detail/index.tsx
src/base/static/state/ducks/app-config.d.ts
src/base/static/utils/dashboard-utils.tsx
src/flavors/bellevue-bike-share/config.json
src/flavors/columbia/config.json
src/flavors/garfield/config.json
src/flavors/kittitas-firewise/config.json
src/flavors/kittitas-vsp/config.json
src/flavors/palouse/config.json
src/flavors/pbdurham/config.json
src/flavors/spokane/config.json

Several UI tweaks/fixes:
Closes: https://github.com/jalMogo/mgmt/issues/376
Closes: https://github.com/jalMogo/mgmt/issues/378
Closes: https://github.com/jalMogo/mgmt/issues/323
Closes: https://github.com/jalMogo/mgmt/issues/377
Closes: https://github.com/jalMogo/mgmt/issues/357

UI updates

---

src/flavors/creatingcascadia/config.json

This PR updates the form in preparation for ingestion, so that it will be generalized across all location types.

fix(creatingcascadiaConfig)

---

src/base/static/state/ducks/places.js

Closes: https://github.com/jalMogo/mgmt/issues/380

fix(placesDuck): duplicate Places when routing from the PlaceList

---

src/flavors/garfield/config.json
src/flavors/palouse/config.json

Add row to stewardship actions table reporting number of actions by WAU.

refactor: update whitman and garfield dashboard configs

---

src/base/static/components/atoms/typography.js
src/base/static/components/molecules/map-controls.tsx
src/base/static/components/organisms/featured-places-menu.tsx
src/base/static/components/organisms/featured-places-navigator.tsx
src/base/static/components/organisms/left-sidebar.tsx
src/base/static/components/organisms/place-filter-menu.tsx
src/base/static/components/organisms/right-sidebar.tsx
src/base/static/components/organisms/site-header.tsx
src/base/static/state/ducks/featured-places-config.d.ts
src/base/static/state/ducks/featured-places-config.js
src/flavors/argentina/config.json
src/flavors/argentina/static/css/custom.css

This PR:
* adds stable `classNames` (in BEM syntax) to various components to support custom styling
* adds a filter menu to the `argentina` flavor
* adds a new Featured Places menu to the header

Updates to support Argentina 2.0

---

package-lock.json
package.json

chore(package.json): npm audit fix

---

src/base/static/components/form-fields/types/rich-textarea-field-response.js
src/base/static/components/molecules/user-menu.tsx
src/base/static/components/organisms/dashboard/line-chart.tsx
src/base/static/components/organisms/right-sidebar.tsx
src/base/static/components/organisms/site-header.tsx
src/base/static/utils/expression/__tests__/expression.test.js
src/base/static/utils/expression/definitions/index.tsx
src/flavors/argentina/config.json
src/flavors/columbia/config.json
src/flavors/quepasa/config.json
src/flavors/spokane/config.json

chore: fix build errors

---

src/flavors/quepasa/config.json

Modification and addition of fields in the "Water quality" form

Changes in "Calidad de agua" form

---

package-lock.json
package.json

Revert "chore(deps): bump emotion-theming from 10.0.19 to 11.0.0"

---

package-lock.json
package.json

Revert "chore(deps): bump glob from 7.2.3 to 10.3.10"
